Update patch set 15
Patch Set 15:

```
> fatal error: QueryPerformanceFrequency overflow 32 bit divider, check nosplit discussion to proceed
> ```
> I do not understand what I am suppose to do here (as a Go user).
> I wonder if you want to do something about it before I submit this CL.
> 
> Alex

Please apply following patch (or basically add println after frequency reading at line #352) and show me debug prints you get and what is the CPU you use (its frequency).
Your hardware tells obscure clock frequency which can not be used with timediv(), wine reports 10Mhz counter which is safe for 32-bits division

diff --git a/src/runtime/os_windows.go b/src/runtime/os_windows.go
index 672cc10..6e0d86f 100644
--- a/src/runtime/os_windows.go
+++ b/src/runtime/os_windows.go
@@ -354,6 +354,8 @@ func initWine(k32 uintptr) {
                throw("QueryPerformanceFrequency syscall returned zero, running on unsupported hardware")
        }
 
+       println("freq:", tmp)
+
        // This should not overflow, it is a number of ticks of the performance counter per second,
        // its resolution is at most 10 per usecond (on Wine, even smaller on real hardware), so it will be at most 10 millions here,
        // panic if overflows.

Patch-set: 15
Reviewer: Gerrit User 17055 <17055@62eb7196-b449-3ce5-99f1-c037f21e1705>