Update patch set 2
Patch Set 2:

> Patch Set 1:
> Consequently, some other tests are failing:
> 
> --- FAIL: TestDependencies (2.38s)
> 	deps_test.go:500: unexpected dependency: net imports [os/signal]
> FAIL
> FAIL	go/build	2.782s
> 
> → TestDependencies is failing because we now imports the os/signal
> package on Plan 9.

I think we can provide some internal runtime function to net package
to "ignore" certain notes once received. This will also fix the 2nd
problem too.

> --- FAIL: TestTCPReadWriteAllocs (0.02s)
> 	tcpsock_test.go:503: got 2; want 0
> FAIL
> FAIL	net	2.458s
> 
> → TestTCPReadWriteAllocs is failing because we now allocate memory
> for two channels in newAsyncIO, to handle the signal and results.

If new runtime interface is not acceptable, and having net dependent
on os/signal is acceptable, I'm wondering if we can just use a package
global channel for this purpose? (We might need to add some unblocking
receive operation on the channel after each async IO operation to avoid
blocking the runtime.)

Patch-set: 2