Update patch set 8
Patch Set 8:

> Patch Set 7:
> 
> > > I think this is fine for 1.15.  Thanks.
> > 
> > So, you think I could submit now, for beta1?
> 
> Yes, go for it.
> 
> > And also, hints for building downrev gdb would be lovely, channels still come out funny in gdb7, not quite sure why without a live one to play with.
> 
> What goes wrong when you try?

It looks like this (not sure how it will format in Gerrit, oh well):

g++ -g -O2   -I. -I. -I./common -I./config -DLOCALEDIR="\"/usr/local/share/locale\"" -DHAVE_CONFIG_H -I./../include/opcode -I./../opcodes/.. -I./../readline/.. -I./../zlib -I../bfd -I./../bfd -I./../include -I../libdecnumber -I./../libdecnumber  -I./gnulib/import -Ibuild-gnulib/import   -DTUI=1  -I/usr/include/python2.7 -I/usr/include/python2.7 -Wall -Wpointer-arith -Wno-unused -Wunused-value -Wunused-function -Wno-switch -Wno-char-subscripts -Wempty-body -Wunused-but-set-parameter -Wunused-but-set-variable -Wno-sign-compare -Wno-write-strings -Wno-narrowing -Wformat-nonliteral  -c -o linux-ptrace.o -MT linux-ptrace.o -MMD -MP -MF .deps/linux-ptrace.Tpo ./nat/linux-ptrace.c
In file included from ./nat/linux-ptrace.c:20:
./nat/linux-ptrace.h:175:22: error: expected identifier before numeric constant
  175 | # define TRAP_HWBKPT 4
      |                      ^
./nat/linux-ptrace.h:175:22: error: expected ‘}’ before numeric constant
In file included from /usr/include/signal.h:58,
                 from build-gnulib/import/signal.h:52,
                 from /usr/include/x86_64-linux-gnu/sys/wait.h:36,
                 from ./common/gdb_wait.h:23,
                 from ./nat/linux-ptrace.c:24:
/usr/include/x86_64-linux-gnu/bits/siginfo-consts.h:156:1: note: to match this ‘{’
  156 | {
      | ^
In file included from ./nat/linux-ptrace.c:20:
./nat/linux-ptrace.h:175:22: error: expected unqualified-id before numeric constant
  175 | # define TRAP_HWBKPT 4
      |                      ^
In file included from /usr/include/features.h:446,
                 from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
                 from /usr/include/stdio.h:27,
                 from build-gnulib/import/stdio.h:43,
                 from ./common/common-defs.h:31,
                 from ./nat/linux-ptrace.c:19:
/usr/include/x86_64-linux-gnu/sys/wait.h:147:1: error: expected declaration before ‘}’ token
  147 | __END_DECLS
      | ^~~~~~~~~~~
make[2]: *** [Makefile:2360: linux-ptrace.o] Error 1
make[2]: Leaving directory '/usr/local/google/home/drchase/work/gdb-7.12/gdb'
make[1]: *** [Makefile:9162: all-gdb] Error 2
make[1]: Leaving directory '/usr/local/google/home/drchase/work/gdb-7.12'
make: *** [Makefile:851: all] Error 2

Patch-set: 8