Update patch set 4
Patch Set 4: Code-Review-1

I see test failures when running with this patch. These need to be fixed before this can be merged:

--- FAIL: TestReader (0.24s)
        reader_test.go:411: r.zip: copying contents: zip: checksum error (want <nil>)
        reader_test.go:411: r.zip: copying contents: zip: checksum error (want <nil>)
        reader_test.go:411: r.zip: copying contents: zip: checksum error (want <nil>)
        reader_test.go:411: r.zip: copying contents: zip: checksum error (want <nil>)
        reader_test.go:411: r.zip: copying contents: zip: checksum error (want <nil>)
        reader_test.go:411: r.zip: copying contents: zip: checksum error (want <nil>)
FAIL
FAIL    archive/zip     0.299s

--- FAIL: TestPalettedDecodeConfig (0.06s)
        reader_test.go:309: basn3p08: png: invalid format: invalid checksum
        reader_test.go:309: basn3p08-trns: png: invalid format: invalid checksum
FAIL
FAIL    image/png       0.374s

Patch-set: 4
Label: Code-Review=-1