Update patch set 7
Patch Set 7:

> Patch Set 7:
> 
> Ping, Chad. Thanks for working on this. FYI I tried and got the following failures with your patch applied on top of today's tip = 8aa316c139:
> 
> ---- 8< ----
> --- FAIL: TestNilcheckAddrOffPtr (0.00s)
>         export_test.go:140: bad SP type: want uintptr, have SSA
> --- FAIL: TestIsNonNilcheckAddrOffPtr (0.00s)
>         export_test.go:140: bad SB type: want uintptr, have SSA
> --- FAIL: TestNilcheckAddrPtrOffPtr (0.00s)
>         export_test.go:140: bad SP type: want uintptr, have SSA
> FAIL
> FAIL    cmd/compile/internal/ssa        0.091s

Thanks for the feedback, Kirill.  I've asked Balaram to follow up on this work, but currently it's taking a back seat to his work on ChaCha.  Hopefully, we'll have an update in the coming weeks.

Patch-set: 7
Reviewer: Gerrit User 25690 <25690@62eb7196-b449-3ce5-99f1-c037f21e1705>