Update patch set 1
Patch Set 1:

> I have no idea why this fails.
> 
> ```
> Building Go cmd/dist using C:\workdir\go1.4
> Building Go toolchain1 using C:\workdir\go1.4.
> Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
> Building Go toolchain2 using go_bootstrap and Go toolchain1.
> # runtime
> asm: invalid instruction: 00019 (C:\workdir\go\src\runtime\sys_windows_386.s:255)	SUBL	$runtime.callbackasm(CX), AX, R???1
> asm: assembly failed
> go tool dist: FAILED: C:\workdir\go\pkg\tool\windows_386\go_bootstrap install -gcflags=all= -ldflags=all= -i cmd/asm cmd/cgo cmd/compile cmd/link: exit status 2
> 
> 
> Error: build failed: make script failed: exit status 1
> ```
> 
> I have spent some time on this, but no luck. I will have to leave for later.
> 
> Please, let me know, if you know why it is broken.

The failing instruction is

	SUBL	$runtime·callbackasm(SB), AX

This instruction assumes that it can use an immediate value to get the address of a function.  That of course is not true when using PIE.

But I have to admit that I don't know why it fails in this way.  I don't see a failure from "GOOS=windows GOARCH=386 go build -buildmode=pie runtime".

Hmmm, I think I see why.  Currently using -buildmode=pie on Windows does not set codegenArg to "-shared".  This CL does make that change.  And indeed I do see the same error if I run "GOOS=windows GOARCH=386 go build -buildmode=pie -asmflags=all=-shared runtime".

Assuming that -buildmode=pie works today on Windows, then you should not set codegenArg in this CL.



As a separate note, this CL should update the release notes to indicate the change in default.

Patch-set: 1
CC: Gerrit User 5206 <5206@62eb7196-b449-3ce5-99f1-c037f21e1705>