Update patch set 3
Patch Set 3:

> > Sorry I never looked at this before.  This seems much more complex than is necessary.  The map assignment is always going to copy the value.  So you should be able to do
> >     kv := reflect.New(mtyp.Key())
> >     kz := reflect.Zero(mtyp.Key())
> >     for i := 0; i < n; i++ {
> >         key := decodeIntoValue(..., kv.Elem(), ...)
> >         kv.Elem().Set(kz)
> >     }
> > At least, I don't see why that wouldn't work for every type.
> 
> This approach fails in tests:
> 
> func (dec *Decoder) decodeMap(mtyp reflect.Type, state *decoderState, value reflect.Value, keyOp, elemOp decOp, ovfl error) {
> 	n := int(state.decodeUint())
> 	if value.IsNil() {
> 		value.Set(reflect.MakeMapWithSize(mtyp, n))
> 	}
> 	keyIsPtr := mtyp.Key().Kind() == reflect.Ptr
> 	elemIsPtr := mtyp.Elem().Kind() == reflect.Ptr
> 	keyInstr := &decInstr{keyOp, 0, nil, ovfl}
> 	elemInstr := &decInstr{elemOp, 0, nil, ovfl}
> 	key := reflect.New(mtyp.Key())
> 	keyZ := reflect.Zero(mtyp.Key())
> 	elem := reflect.New(mtyp.Elem())
> 	elemZ :=  reflect.Zero(mtyp.Elem())
> 	for i := 0; i < n; i++ {
> 		key = decodeIntoValue(state, keyOp, keyIsPtr, key.Elem(), keyInstr)
> 		elem = decodeIntoValue(state, elemOp, elemIsPtr, elem.Elem(), elemInstr)
> 		value.SetMapIndex(key, elem)
> 		key.Elem().Set(keyZ)
> 		elem.Elem().Set(elemZ)
> 	}
> }
> 
> 
> --- FAIL: TestEndToEnd (0.00s)
> panic: reflect: call of reflect.Value.Elem on string Value [recovered]
> 	panic: reflect: call of reflect.Value.Elem on string Value [recovered]
> 	panic: reflect: call of reflect.Value.Elem on string Value

OK, clearly I have made some dumb mistake in the code.  Figure out where Elem is being called incorrectly.


> At the bottom of the decode.go is allocation function that I believe addresses that with a comment:
> 
> // Gob depends on being able to take the address
> // of zeroed Values it creates, so use this wrapper instead
> // of the standard reflect.Zero.
> // Each call allocates once.
> func allocValue(t reflect.Type) reflect.Value {
> 	return reflect.New(t).Elem()
> }

I was trying to do the same in my code.  That's why I called reflect.New.


> Let me try to explain my understanding of why the different behavior is needed with pointers. I think the reason is shallow copying into the map.

Sure, but I was trying to avoid that problem by assigning zero to the value each time through the loop.


> That's why I add all the new tests to this CL, they tackle this behavior. Even before I added them there was fortunately already one that was catching it. That's how I came to this convoluted solution.

I'm sorry, the convoluted solution is too convoluted.  I do not think we should adopt it.

Patch-set: 3