Update patch set 3
Patch Set 3:

I don't think the trybot failure is related to this change... should I open an issue? 


runtime: pointer 0xc000418000 to unused region of span span.base()=0xc000418000 span.limit=0xc00041a000 span.state=1
runtime: found in object at *(0xc000649950+0x0)
object=0xc000649950 s.base()=0xc000648000 s.limit=0xc000649fe0 s.spanclass=8 s.elemsize=48 s.state=mSpanInUse
 *(object+0) = 0xc000418000 <==
 *(object+8) = 0x0
 *(object+16) = 0x200
 *(object+24) = 0x0
 *(object+32) = 0x0
 *(object+40) = 0x0
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)

runtime stack:
runtime.throw(0x9f24b9, 0x3e)
	/tmp/workdir/go/src/runtime/panic.go:617 +0x72 fp=0x7fffdf7f9dc0 sp=0x7fffdf7f9d90 pc=0x42d1f2
runtime.findObject(0xc000418000, 0xc000649950, 0x0, 0x80136ddb8, 0xc00002d270, 0x0)
	/tmp/workdir/go/src/runtime/mbitmap.go:397 +0x3b4 fp=0x7fffdf7f9e10 sp=0x7fffdf7f9dc0 pc=0x415284
runtime.scanobject(0xc000649950, 0xc00002d270)
	/tmp/workdir/go/src/runtime/mgcmark.go:1161 +0x216 fp=0x7fffdf7f9ea0 sp=0x7fffdf7f9e10 pc=0x4208d6
runtime.gcDrain(0xc00002d270, 0x3)
	/tmp/workdir/go/src/runtime/mgcmark.go:919 +0x217 fp=0x7fffdf7f9ef8 sp=0x7fffdf7f9ea0 pc=0x4200e7
runtime.gcBgMarkWorker.func2()
	/tmp/workdir/go/src/runtime/mgc.go:1873 +0x80 fp=0x7fffdf7f9f38 sp=0x7fffdf7f9ef8 pc=0x454180
runtime.systemstack(0x7fffdf7f9f90)
	/tmp/workdir/go/src/runtime/asm_amd64.s:351 +0x66 fp=0x7fffdf7f9f40 sp=0x7fffdf7f9f38 pc=0x456746
runtime.mstart()
	/tmp/workdir/go/src/runtime/proc.go:1153 fp=0x7fffdf7f9f48 sp=0x7fffdf7f9f40 pc=0x431740

Patch-set: 3
Reviewer: Gerrit User 13437 <13437@62eb7196-b449-3ce5-99f1-c037f21e1705>