Update patch set 9
Patch Set 9:

> Patch Set 9: TryBot-Result-1
> 
> 7 of 19 TryBots failed:
> Failed on linux-amd64: https://storage.googleapis.com/go-build-log/74f8abd1/linux-amd64_f22a2b69.log
> Failed on linux-386: https://storage.googleapis.com/go-build-log/74f8abd1/linux-386_2b48da12.log
> Failed on freebsd-amd64-12_0: https://storage.googleapis.com/go-build-log/74f8abd1/freebsd-amd64-12_0_6de97696.log
> Failed on js-wasm: https://storage.googleapis.com/go-build-log/74f8abd1/js-wasm_7d7b11f0.log
> Failed on windows-amd64-2016: https://storage.googleapis.com/go-build-log/74f8abd1/windows-amd64-2016_89cbcd0e.log
> Failed on windows-386-2008: https://storage.googleapis.com/go-build-log/74f8abd1/windows-386-2008_8598f183.log
> Failed on openbsd-amd64-64: https://storage.googleapis.com/go-build-log/74f8abd1/openbsd-amd64-64_6b01f0db.log
> 
> Consult https://build.golang.org/ to see whether they are new failures.

Alan, the same error is causing the build failures:
--- FAIL: TestDocsUpToDate (0.00s)
    help_test.go:26: alldocs.go is not up to date; run mkalldocs.sh to regenerate it

Please take a look.

Patch-set: 9
CC: Gerrit User 5137 <5137@62eb7196-b449-3ce5-99f1-c037f21e1705>