runtime/cgo: replace nil with NULL
While working on standalone builds of gomobile bindings, I ran into
error on the form:

gcc_darwin_arm.c:30:31: error: ambiguous expansion of macro 'nil' [-Werror,-Wambiguous-macro]
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/MacTypes.h:94:15: note: expanding this definition of 'nil'

I don't know why they appear now, but using NULL instead of nil
seems to fix it.

Change-Id: I8e9660a68c6c351e592684d03d529f0d182c0493