Update patch set 26
Patch Set 26:

Only 4 tests that still fail, 3 of them I know where to look for and can reproduce running test separately, but this one I don't understand at all and also can't reproduce separately because when I try cd /usr/local/go/src/cmd/go and do go test, my computer hangs. I can only see the result doing ./all.bash

go test proxy running at GOPROXY=http://127.0.0.1:52280/mod
--- FAIL: TestScript (0.00s)
    --- FAIL: TestScript/mod_query_empty (1.24s)
        script_test.go:191: 
            # If the proxy serves a bogus result for the @latest version,
            # reading that version should cause 'go get' to fail. (0.127s)
            # If @v/list is empty, the 'go' command should still try to resolve
            # other module paths. (0.088s)
            > env GOPROXY=file:///$WORK/emptysub
            > cp go.mod.orig go.mod
            > go get -d example.com/join/subpkg
            [stderr]
            go: finding example.com/join/subpkg latest
            go get example.com/join/subpkg: module example.com/join/subpkg: no commits
            [exit status 1]
            FAIL: testdata/script/mod_query_empty.txt:17: unexpected command failure
            
FAIL
FAIL    cmd/go  60.234s

script_test.go:191 points to a place that doesn't make sense to me at all. PS vscode tools don't work with my new compiler yet so I have to grep for everything, can't jump around by clicking on things. It's funny how much harder it is to fix things when basically you only have a go build, notepad and grep :D

Any ideas what is going on please and what I can try to fix this test? Thanks

Patch-set: 26
Reviewer: Gerrit User 15355 <15355@62eb7196-b449-3ce5-99f1-c037f21e1705>