Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [golang/try/x_tools-gotip-linux-amd64](https://cr-buildbucket.appspot.com/build/8764802829682761617) has failed with summary [(view all results)](https://go-review.googlesource.com/c/536215?checksPatchset=1&tab=checks):

---
**FAILURE**

* go on master ([change 536215](https://go-review.googlesource.com/c/go/+/536215/1))
* tools on master ([commit 92a8009](https://go.googlesource.com/tools/+/92a8009ce00a3d72bb7b406b17a48d1105cd4e7f))

error: failed to run "test golang.org/x/tools module": exit status 1
* ["test golang.org/x/tools module" (combined output)](https://logs.chromium.org/logs/golang/buildbucket/cr-buildbucket/8764802829682761617/+/u/step/25/log/2)

Patch-set: 1
Tag: autogenerated:cq:dry-run:1699629668
Attention: {"person_ident":"Gerrit User 14570 \u003c14570@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}