Update patch set 3
Patch Set 3:

This CL has failed the run. Reason:

Tryjob [golang/try/x_tools-gotip-linux-amd64](https://cr-buildbucket.appspot.com/build/8747738573845962609) has failed with summary ([view all results](https://go-review.googlesource.com/c/586137?checksPatchset=3&tab=checks)):

---
**FAILURE**

* go on master ([change 586137](https://go-review.googlesource.com/c/go/+/586137/3))
* tools on master ([commit 1f300c9](https://go.googlesource.com/tools/+/1f300c9005ddf5667162932a2dd16cad9f461cd8))

Error: `failed to run "make.bash": exit status 2`

Links:
* ["make.bash" (combined output)](https://logs.chromium.org/logs/golang/buildbucket/cr-buildbucket/8747738573845962609/+/u/step/12/log/2)

Patch-set: 3
Tag: autogenerated:cq:dry-run:1715903413
Attention: {"person_ident":"Gerrit User 13315 \u003c13315@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"ADD","reason":"ps#3: Tryjobs failed"}