Update patch set 7
Patch Set 7: Code-Review+1

> Patch Set 6:
> 
> When I run all.bash on linux/arm with this CL I get the following failure in:
> 
>   --- FAIL: TestTimePprof (0.21s)
> 	crash_test.go:95: testprog TimeProf exit status: signal: segmentation fault
> 	crash_test.go:633: : open : no such file or directory
> 		failed to fetch any source profiles
> 	crash_test.go:635: exit status 1
> FAIL
> FAIL	runtime	111.670s
> 
> It does not occur when running all.bash on tip. I'm not how it is related to this CL, will look into it.

Looks like this was caused by something else. I can no longer reproduce the failure.

FWIW, I did the same sanity checks as Paul, though not using gdb but by using print() debugging ;) on an Raspberry Pi 3 (with AT_HWCAP having hwcap_IDIVA set). Also using GODEBUGCPU=IDIVA=0 leads to the expected result of internal/cpu.ARM.HasIDIVA = false

Thanks

Patch-set: 7
Reviewer: Gerrit User 19560 <19560@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: Code-Review=+1