Update patch set 1
Patch Set 1: Code-Review+1

+ Fixes #12035

IMO the real reason is that in the test (c + runtime) creates more thread stacks than can fit in the user virtual space.

On 32bit with a kernel split (CONFIG_VMSPLIT_2G=y) it is 2GB, i.e. 2g/8g ~> max 250 threads / process. FWIW a simple c test shows:

./create-threads
ERROR: creating thread 252
	return code from pthread_create() is 11
	pthread_create failed: Resource temporarily unavailable
ulimit -Ss 1024 && ./create-threads
ERROR: creating thread 2028
	return code from pthread_create() is 11
	pthread_create failed: Resource temporarily unavailable

For some background, usually the 32bit kernels split the kernel/user virtual space at 1g/3g, the 2g/2g split was set in the recent rpi kernel to avoid wasting of usable RAM:
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=98520

As I understand it, the runtime manages it's stacks on heap, how big 'virtual' thread stack size Go needs? E.g. I've run successfully ulimit -Ss 1024 ./all.bash on rpi2.

Would it make a sense to set for arm/381 something lower than the default 8M?
https://github.com/golang/go/blob/master/src/runtime/cgo/gcc_linux_arm.c#L16

Thanks.

Patch-set: 1
Reviewer: Gerrit User 8550 <8550@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: Code-Review=+1