Update patch set 12
Patch Set 12:

Thx // +build compiler_bootstrap is the best one :)

When trying method 2) adding this file everywhere needed

// +build compiler_bootstrap
type wrapper = interface{}

I dont think it's going to work because I get this error messages

gert@gert /usr/local/go/src:#32913> ./all.bash 
Building Go cmd/dist using /usr/local/go1.
Building Go toolchain1 using /usr/local/go1.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
/usr/local/go/src/compress/flate/huffman_bit_writer.go:172:9: cannot use InternalError("writeBytes with unfinished bits") (type InternalError) as type error in assignment:
        InternalError does not implement error (wrong type for Unwrap method)
                have Unwrap() interface {}
                want Unwrap() wrapper

Which indicate if I am not mistaken it successfully replaced wrapper with interface but then the bootstrap type checker isn't happy anymore right? So I need to do method 1) and method 2) or maybe just method 1) ?

Patch-set: 12
Reviewer: Gerrit User 15355 <15355@62eb7196-b449-3ce5-99f1-c037f21e1705>