Update patch set 1
Patch Set 1:

This is an experimental change. In its current state, I'm able to
run all the enabled tests in the net and net/http package (which were
broken since CL 31173), and also enable the various timeout tests.

I'd like to get your (anyone) input about this approach.

Consequently, some other tests are failing:

--- FAIL: TestDependencies (2.38s)
	deps_test.go:500: unexpected dependency: net imports [os/signal]
FAIL
FAIL	go/build	2.782s

→ TestDependencies is failing because we now imports the os/signal
package on Plan 9.

--- FAIL: TestTCPReadWriteAllocs (0.02s)
	tcpsock_test.go:503: got 2; want 0
FAIL
FAIL	net	2.458s

→ TestTCPReadWriteAllocs is failing because we now allocate memory
for two channels in newAsyncIO, to handle the signal and results.

Patch-set: 1
Label: Code-Review=0