Update patch set 10
Change has been successfully cherry-picked as ea2c27fe8204225b4d76ed4a541c6b92afec8dde

8 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: src/go/types/lookup.go
Insertions: 12, Deletions: 4.

@@ -390,15 +390,21 @@
 	if alt != nil {
 		if m.Name() != alt.Name() {
 			return check.sprintf("(missing %s)\n\t\thave %s\n\t\twant %s",
-				mname, check.funcString(alt), check.funcString(m))
+				mname, check.funcString(alt, false), check.funcString(m, false))
 		}
 
 		if Identical(m.typ, alt.typ) {
 			return check.sprintf("(%s has pointer receiver)", mname)
 		}
 
+		altS, mS := check.funcString(alt, false), check.funcString(m, false)
+		if altS == mS {
+			// Would tell the user that Foo isn't a Foo, add package information to disambiguate.  See #54258.
+			altS, mS = check.funcString(alt, true), check.funcString(m, true)
+		}
+
 		return check.sprintf("(wrong type for %s)\n\t\thave %s\n\t\twant %s",
-			mname, check.funcString(alt), check.funcString(m))
+			mname, altS, mS)
 	}
 
 	if isInterfacePtr(V) {
@@ -431,14 +437,16 @@
 	return check.sprintf("type %s is pointer to interface, not interface", T)
 }
 
+// funcString returns a string of the form name + signature for f.
 // check may be nil.
-func (check *Checker) funcString(f *Func) string {
+func (check *Checker) funcString(f *Func, pkgInfo bool) string {
 	buf := bytes.NewBufferString(f.name)
 	var qf Qualifier
-	if check != nil {
+	if check != nil && !pkgInfo {
 		qf = check.qualifier
 	}
 	w := newTypeWriter(buf, qf)
+	w.pkgInfo = pkgInfo
 	w.paramNames = false
 	w.signature(f.typ.(*Signature))
 	return buf.String()
```
```
The name of the file: src/go/types/issues_test.go
Insertions: 122, Deletions: 0.

@@ -12,6 +12,7 @@
 	"go/importer"
 	"go/token"
 	"internal/testenv"
+	"regexp"
 	"sort"
 	"strings"
 	"testing"
@@ -729,3 +730,124 @@
 		}
 	}
 }
+
+func TestIssue54258(t *testing.T) {
+
+	tests := []struct{ main, b, want string }{
+		{ //---------------------------------------------------------------
+			`package main
+import "b"
+type I0 interface {
+	M0(w struct{ f string })
+}
+var _ I0 = b.S{}
+`,
+			`package b
+type S struct{}
+func (S) M0(struct{ f string }) {}
+`,
+			`6:12: cannot use b[.]S{} [(]value of type b[.]S[)] as I0 value in variable declaration: b[.]S does not implement I0 [(]wrong type for method M0[)]
+.*have M0[(]struct{f string /[*] package b [*]/ }[)]
+.*want M0[(]struct{f string /[*] package main [*]/ }[)]`},
+
+		{ //---------------------------------------------------------------
+			`package main
+import "b"
+type I1 interface {
+	M1(struct{ string })
+}
+var _ I1 = b.S{}
+`,
+			`package b
+type S struct{}
+func (S) M1(struct{ string }) {}
+`,
+			`6:12: cannot use b[.]S{} [(]value of type b[.]S[)] as I1 value in variable declaration: b[.]S does not implement I1 [(]wrong type for method M1[)]
+.*have M1[(]struct{string /[*] package b [*]/ }[)]
+.*want M1[(]struct{string /[*] package main [*]/ }[)]`},
+
+		{ //---------------------------------------------------------------
+			`package main
+import "b"
+type I2 interface {
+	M2(y struct{ f struct{ f string } })
+}
+var _ I2 = b.S{}
+`,
+			`package b
+type S struct{}
+func (S) M2(struct{ f struct{ f string } }) {}
+`,
+			`6:12: cannot use b[.]S{} [(]value of type b[.]S[)] as I2 value in variable declaration: b[.]S does not implement I2 [(]wrong type for method M2[)]
+.*have M2[(]struct{f struct{f string} /[*] package b [*]/ }[)]
+.*want M2[(]struct{f struct{f string} /[*] package main [*]/ }[)]`},
+
+		{ //---------------------------------------------------------------
+			`package main
+import "b"
+type I3 interface {
+	M3(z struct{ F struct{ f string } })
+}
+var _ I3 = b.S{}
+`,
+			`package b
+type S struct{}
+func (S) M3(struct{ F struct{ f string } }) {}
+`,
+			`6:12: cannot use b[.]S{} [(]value of type b[.]S[)] as I3 value in variable declaration: b[.]S does not implement I3 [(]wrong type for method M3[)]
+.*have M3[(]struct{F struct{f string /[*] package b [*]/ }}[)]
+.*want M3[(]struct{F struct{f string /[*] package main [*]/ }}[)]`},
+
+		{ //---------------------------------------------------------------
+			`package main
+import "b"
+type I4 interface {
+	M4(_ struct { *string })
+}
+var _ I4 = b.S{}
+`,
+			`package b
+type S struct{}
+func (S) M4(struct { *string }) {}
+`,
+			`6:12: cannot use b[.]S{} [(]value of type b[.]S[)] as I4 value in variable declaration: b[.]S does not implement I4 [(]wrong type for method M4[)]
+.*have M4[(]struct{[*]string /[*] package b [*]/ }[)]
+.*want M4[(]struct{[*]string /[*] package main [*]/ }[)]`},
+
+		{ //---------------------------------------------------------------
+			`package main
+import "b"
+type t struct{ A int }
+type I5 interface {
+	M5(_ struct {b.S;t})
+}
+var _ I5 = b.S{}
+`,
+			`package b
+type S struct{}
+type t struct{ A int }
+func (S) M5(struct {S;t}) {}
+`,
+			`7:12: cannot use b[.]S{} [(]value of type b[.]S[)] as I5 value in variable declaration: b[.]S does not implement I5 [(]wrong type for method M5[)]
+.*have M5[(]struct{b[.]S; b[.]t}[)]
+.*want M5[(]struct{b[.]S; t}[)]`},
+	}
+
+	test := func(main, imported, want string) {
+		re := regexp.MustCompile(want)
+		a := mustTypecheck("b", imported, nil)
+		bast := mustParse(fset, "", main)
+		conf := Config{Importer: importHelper{pkg: a}}
+		_, err := conf.Check(bast.Name.Name, fset, []*ast.File{bast}, nil)
+		if err == nil {
+			t.Errorf("Expected failure, but it did not")
+		} else if got := err.Error(); !re.MatchString(got) {
+			t.Errorf("Wanted match for\n%s\n but got \n%s", want, got)
+		} else if testing.Verbose() {
+			t.Logf("Saw expected\n%s", err.Error())
+		}
+	}
+	for _, t := range tests {
+		test(t.main, t.b, t.want)
+	}
+}
```
```
The name of the file: src/cmd/compile/internal/types2/issues_test.go
Insertions: 121, Deletions: 0.

@@ -10,6 +10,7 @@
 	"cmd/compile/internal/syntax"
 	"fmt"
 	"internal/testenv"
+	"regexp"
 	"sort"
 	"strings"
 	"testing"
@@ -703,3 +704,123 @@
 		}
 	}
 }
+
+func TestIssue54258(t *testing.T) {
+	tests := []struct{ main, b, want string }{
+		{ //---------------------------------------------------------------
+			`package main
+import "b"
+type I0 interface {
+	M0(w struct{ f string })
+}
+var _ I0 = b.S{}
+`,
+			`package b
+type S struct{}
+func (S) M0(struct{ f string }) {}
+`,
+			`6:12: cannot use b[.]S{} [(]value of type b[.]S[)] as I0 value in variable declaration: b[.]S does not implement I0 [(]wrong type for method M0[)]
+.*have M0[(]struct{f string /[*] package b [*]/ }[)]
+.*want M0[(]struct{f string /[*] package main [*]/ }[)]`},
+
+		{ //---------------------------------------------------------------
+			`package main
+import "b"
+type I1 interface {
+	M1(struct{ string })
+}
+var _ I1 = b.S{}
+`,
+			`package b
+type S struct{}
+func (S) M1(struct{ string }) {}
+`,
+			`6:12: cannot use b[.]S{} [(]value of type b[.]S[)] as I1 value in variable declaration: b[.]S does not implement I1 [(]wrong type for method M1[)]
+.*have M1[(]struct{string /[*] package b [*]/ }[)]
+.*want M1[(]struct{string /[*] package main [*]/ }[)]`},
+
+		{ //---------------------------------------------------------------
+			`package main
+import "b"
+type I2 interface {
+	M2(y struct{ f struct{ f string } })
+}
+var _ I2 = b.S{}
+`,
+			`package b
+type S struct{}
+func (S) M2(struct{ f struct{ f string } }) {}
+`,
+			`6:12: cannot use b[.]S{} [(]value of type b[.]S[)] as I2 value in variable declaration: b[.]S does not implement I2 [(]wrong type for method M2[)]
+.*have M2[(]struct{f struct{f string} /[*] package b [*]/ }[)]
+.*want M2[(]struct{f struct{f string} /[*] package main [*]/ }[)]`},
+
+		{ //---------------------------------------------------------------
+			`package main
+import "b"
+type I3 interface {
+	M3(z struct{ F struct{ f string } })
+}
+var _ I3 = b.S{}
+`,
+			`package b
+type S struct{}
+func (S) M3(struct{ F struct{ f string } }) {}
+`,
+			`6:12: cannot use b[.]S{} [(]value of type b[.]S[)] as I3 value in variable declaration: b[.]S does not implement I3 [(]wrong type for method M3[)]
+.*have M3[(]struct{F struct{f string /[*] package b [*]/ }}[)]
+.*want M3[(]struct{F struct{f string /[*] package main [*]/ }}[)]`},
+
+		{ //---------------------------------------------------------------
+			`package main
+import "b"
+type I4 interface {
+	M4(_ struct { *string })
+}
+var _ I4 = b.S{}
+`,
+			`package b
+type S struct{}
+func (S) M4(struct { *string }) {}
+`,
+			`6:12: cannot use b[.]S{} [(]value of type b[.]S[)] as I4 value in variable declaration: b[.]S does not implement I4 [(]wrong type for method M4[)]
+.*have M4[(]struct{[*]string /[*] package b [*]/ }[)]
+.*want M4[(]struct{[*]string /[*] package main [*]/ }[)]`},
+
+		{ //---------------------------------------------------------------
+			`package main
+import "b"
+type t struct{ A int }
+type I5 interface {
+	M5(_ struct {b.S;t})
+}
+var _ I5 = b.S{}
+`,
+			`package b
+type S struct{}
+type t struct{ A int }
+func (S) M5(struct {S;t}) {}
+`,
+			`7:12: cannot use b[.]S{} [(]value of type b[.]S[)] as I5 value in variable declaration: b[.]S does not implement I5 [(]wrong type for method M5[)]
+.*have M5[(]struct{b[.]S; b[.]t}[)]
+.*want M5[(]struct{b[.]S; t}[)]`},
+	}
+
+	test := func(main, imported, want string) {
+		re := regexp.MustCompile(want)
+		a := mustTypecheck("b", imported, nil)
+		bast := mustParse("", main)
+		conf := Config{Importer: importHelper{pkg: a}}
+		_, err := conf.Check(bast.PkgName.Value, []*syntax.File{bast}, nil)
+		if err == nil {
+			t.Errorf("Expected failure, but it did not")
+		} else if got := err.Error(); !re.MatchString(got) {
+			t.Errorf("Wanted match for\n%s\n but got \n%s", want, got)
+		} else if testing.Verbose() {
+			t.Logf("Saw expected\n%s", err.Error())
+		}
+	}
+	for _, t := range tests {
+		test(t.main, t.b, t.want)
+	}
+}
```
```
The name of the file: src/go/types/object.go
Insertions: 7, Deletions: 0.

@@ -9,6 +9,8 @@
 	"fmt"
 	"go/constant"
 	"go/token"
+	"unicode"
+	"unicode/utf8"
 )
 
 // An Object describes a named language entity such as a package,
@@ -57,6 +59,11 @@
 	setScopePos(pos token.Pos)
 }
 
+func isExported(name string) bool {
+	ch, _ := utf8.DecodeRuneInString(name)
+	return unicode.IsUpper(ch)
+}
+
 // Id returns name if it is exported, otherwise it
 // returns the name qualified with the package path.
 func Id(pkg *Package, name string) string {
```
```
The name of the file: test/fixedbugs/issue54258.dir/main.go
Insertions: 0, Deletions: 73.

@@ -1,73 +0,0 @@
-// Copyright 2022 The Go Authors. All rights reserved.
-// Use of this source code is governed by a BSD-style
-// license that can be found in the LICENSE file.
-
-package main
-
-import "./b"
-
-type I0 interface {
-	M0(w struct{ f string })
-}
-
-var _ I0 = b.S{} // ERROR "cannot use b.S.*as I0 value.*wrong type for method M0.*\n.* package test/b .*\n.* package main "
-
-type I1 interface {
-	M1(x struct{ string })
-}
-
-var _ I1 = b.S{} // ERROR "cannot use b.S.*as I1 value.*wrong type for method M1.*\n.* package test/b .*\n.* package main "
-
-type I2 interface {
-	M2(y struct{ f struct{ f string } })
-}
-
-var _ I2 = b.S{} // ERROR "cannot use b.S.*as I2 value.*wrong type for method M2.*\n.* package test/b .*\n.* package main "
-
-type I3 interface {
-	M3(z struct{ F struct{ f string } })
-}
-
-var _ I3 = b.S{} // ERROR "cannot use b.S.*as I3 value.*wrong type for method M3.*\n.* package test/b .*\n.* package main "
-
-type t struct{ A int }
-
-type I4 interface {
-	M4(_ struct {
-		*string
-	})
-}
-
-var _ I4 = b.S{} // ERROR "cannot use b.S.*as I4 value.*wrong type for method M4.*\n.* package test/b .*\n.* package main "
-
-type I5 interface {
-	M5(_ struct {
-		b.S
-		t
-	})
-}
-
-// This one doesn't need package-comment annotation because the type names actually differ.
-var _ I5 = b.S{} // ERROR "cannot use b.S.*as I5 value.*wrong type for method M5.*\n"
-
-func main() {}
-
-// Original error messages (before changing type from result to arg)
-// ./main.go:13:12: cannot use b.S{} (value of type b.S) as I0 value in variable declaration: b.S does not implement I0 (wrong type for method M0)
-// 		have M0() (struct{f string /* package test/b */ })
-// 		want M0() (struct{f string /* package main */ })
-// ./main.go:19:12: cannot use b.S{} (value of type b.S) as I1 value in variable declaration: b.S does not implement I1 (wrong type for method M1)
-// 		have M1() (struct{string /* package test/b */ })
-// 		want M1() (struct{string /* package main */ })
-// ./main.go:25:12: cannot use b.S{} (value of type b.S) as I2 value in variable declaration: b.S does not implement I2 (wrong type for method M2)
-// 		have M2() (struct{f struct{f string} /* package test/b */ })
-// 		want M2() (struct{f struct{f string} /* package main */ })
-// ./main.go:31:12: cannot use b.S{} (value of type b.S) as I3 value in variable declaration: b.S does not implement I3 (wrong type for method M3)
-// 		have M3() (struct{F struct{f string /* package test/b */ }})
-// 		want M3() (struct{F struct{f string /* package main */ }})
-// .main.go:41:12: cannot use b.S{} (value of type b.S) as I4 value in variable declaration: b.S does not implement I4 (wrong type for method M4)
-// 		have M4() (struct{*string /* package test/b */ })
-// 		want M4() (struct{*string /* package main */ })
-// .main.go:50:12: cannot use b.S{} (value of type b.S) as I5 value in variable declaration: b.S does not implement I5 (wrong type for method M5)
-// 		have M5() (struct{b.S; b.t})
-// 		want M5() (struct{b.S; t})
```
```
The name of the file: test/fixedbugs/issue54258.dir/b.go
Insertions: 0, Deletions: 32.

@@ -1,32 +0,0 @@
-// Copyright 2022 The Go Authors. All rights reserved.
-// Use of this source code is governed by a BSD-style
-// license that can be found in the LICENSE file.
-
-package b
-
-type S struct{}
-
-func (S) M0(_ struct{ f string }) {
-}
-
-func (S) M1(_ struct{ string }) {
-}
-
-func (S) M2(_ struct{ f struct{ f string } }) {
-}
-
-func (S) M3(_ struct{ F struct{ f string } }) {
-}
-
-type t struct{ A int }
-
-func (S) M4(_ struct {
-	*string
-}) {
-}
-
-func (S) M5(_ struct {
-	S
-	t
-}) {
-}
```
```
The name of the file: src/go/types/typestring.go
Insertions: 20, Deletions: 5.

@@ -59,9 +59,8 @@
 }
 
 // WriteSignature writes the representation of the signature sig to buf,
-// without a leading "func" keyword.
-// The Qualifier controls the printing of
-// package-level objects, and may be nil.
+// without a leading "func" keyword. The Qualifier controls the printing
+// of package-level objects, and may be nil.
 func WriteSignature(buf *bytes.Buffer, sig *Signature, qf Qualifier) {
 	newTypeWriter(buf, qf).signature(sig)
 }
@@ -74,15 +73,16 @@
 	tparams      *TypeParamList // local type parameters
 	paramNames   bool           // if set, write function parameter names, otherwise, write types only
 	tpSubscripts bool           // if set, write type parameter indices as subscripts
+	pkgInfo      bool           // package-annotate first unexported-type field to avoid confusing type description
 }
 
 func newTypeWriter(buf *bytes.Buffer, qf Qualifier) *typeWriter {
-	return &typeWriter{buf, make(map[Type]bool), qf, nil, nil, true, false}
+	return &typeWriter{buf, make(map[Type]bool), qf, nil, nil, true, false, false}
 }
 
 func newTypeHasher(buf *bytes.Buffer, ctxt *Context) *typeWriter {
 	assert(ctxt != nil)
-	return &typeWriter{buf, make(map[Type]bool), nil, ctxt, nil, false, false}
+	return &typeWriter{buf, make(map[Type]bool), nil, ctxt, nil, false, false, false}
 }
 
 func (w *typeWriter) byte(b byte) {
@@ -149,6 +149,16 @@
 			if i > 0 {
 				w.byte(';')
 			}
+
+			// If disambiguating one struct for another, look for the first unexported field.
+			// Do this first in case of nested structs; tag the first-outermost field.
+			pkgAnnotate := false
+			if w.qf == nil && w.pkgInfo && !isExported(f.name) {
+				// note for embedded types, type name is field name, and "string" etc are lower case hence unexported.
+				pkgAnnotate = true
+				w.pkgInfo = false // only tag once
+			}
+
 			// This doesn't do the right thing for embedded type
 			// aliases where we should print the alias name, not
 			// the aliased type (see issue #44410).
@@ -157,6 +167,11 @@
 				w.byte(' ')
 			}
 			w.typ(f.typ)
+			if pkgAnnotate {
+				w.string(" /* package ")
+				w.string(f.pkg.Path())
+				w.string(" */ ")
+			}
 			if tag := t.Tag(i); tag != "" {
 				w.byte(' ')
 				// TODO(rfindley) If tag contains blanks, replacing them with '#'
```
```
The name of the file: test/fixedbugs/issue54258.go
Insertions: 0, Deletions: 7.

@@ -1,7 +0,0 @@
-// errorcheckdir
-
-// Copyright 2022 The Go Authors. All rights reserved.
-// Use of this source code is governed by a BSD-style
-// license that can be found in the LICENSE file.
-
-package ignored
```


Patch-set: 10
Subject: cmd/compile: package-annotate structs when error would be ambiguous
Status: merged
Commit: ea2c27fe8204225b4d76ed4a541c6b92afec8dde
Tag: autogenerated:gerrit:merged
Groups: c3bf8673339674323ddec86b06f804bde8a40bac
Label: Code-Review=+2, a50de9e108d9660c0fc75a46b8f3fd1a85968414 Gerrit User 7392 <7392@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: Run-TryBot=+1, ba0b6d846df18f7844192f065a83bad5a613a44f
Label: TryBot-Result=+1, e3bdd698394a0eb38718b6235f0f0ca79463adf2 Gerrit User 5976 <5976@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: SUBM=+1, ec2a22231529f03bc5e1de4df63be5d806a66069
Submission-id: 422914
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Code-Review: Gerrit User 7392 <7392@62eb7196-b449-3ce5-99f1-c037f21e1705>
Submitted-with: MAY: Hold
Submitted-with: MAY: Run-TryBot: Gerrit User 7061 <7061@62eb7196-b449-3ce5-99f1-c037f21e1705>
Submitted-with: MAY: TryBot-Result: Gerrit User 5976 <5976@62eb7196-b449-3ce5-99f1-c037f21e1705>
Submitted-with: MAY: Auto-Submit
Submitted-with: MAY: TryBot-Bypass
Attention: {"person_ident":"Gerrit User 31647 \u003c31647@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"REMOVE","reason":"Change was submitted"}