reflect: prepare fieldnames for moving to abi/type.go
This CL introduces code that causes a crash compiling
for race detection:

--- FAIL: TestExitHooks (1.40s)
    crash_test.go:141: running /Users/drchase/work/go-quick/bin/go build -o .../testexithooks_.exe
    crash_test.go:147: built testexithooks_ in 319.899811ms
    crash_test.go:141: running /Users/drchase/work/go-quick/bin/go build -o .../testexithooks_-race.exe -race
    ehooks_test.go:62: building testexithooks [-race]: exit status 1
        # internal/abi
        ../../../internal/abi/type.go:569:6: internal compiler error: 'NewName': value .autotmp_64 (v400) incorrectly live at entry

Change-Id: Ia8e88029d29a1210dc7a321578e61336e235f35a