Update patch set 23
Patch Set 23:

(3 comments)

Yeeej working!, still a mystery to me how you manage to compile and debug this in your head :D 

I now can thinker with this specific package thx, no help required at the moment :D

gert@gert /usr/local/go/src/errors:#32913> go test
--- FAIL: TestIs (0.00s)
    --- FAIL: TestIs/#08 (0.00s)
        wrap_test.go:53: Is(either 1 or 3, 1) = false, want true
    --- FAIL: TestIs/#09 (0.00s)
        wrap_test.go:53: Is(either 1 or 3, 3) = false, want true
    --- FAIL: TestIs/#12 (0.00s)
        wrap_test.go:53: Is(uncomparable error, uncomparable error) = false, want true
    --- FAIL: TestIs/#14 (0.00s)
        wrap_test.go:53: Is(uncomparable error, uncomparable error) = false, want true
--- FAIL: TestAs (0.00s)
    --- FAIL: TestAs/1:As(Errorf(...,_pitied_the_fool),_errorT()) (0.00s)
        wrap_test.go:160: match: got false; want true
    --- FAIL: TestAs/10:As(Errorf(...,_path_error),_0xc000050030) (0.00s)
        wrap_test.go:160: match: got false; want true
--- FAIL: TestUnwrap (0.00s)
    wrap_test.go:211: Unwrap(wrap 2) = <nil>, want 1
    wrap_test.go:211: Unwrap(wrap 3) = <nil>, want wrap 2
FAIL
exit status 1
FAIL    errors  0.006s

Patch-set: 23
Reviewer: Gerrit User 15355 <15355@62eb7196-b449-3ce5-99f1-c037f21e1705>