Update patch set 10
Patch Set 10: Run-TryBot+1

Resolved merge conflict.

Previous try-bot failure on openbsd-amd64 was:

--- FAIL: TestWriteToTimeout (0.00s)
	timeout_test.go:655: #1/1: write udp 127.0.0.1:23069->127.0.0.1:34789: sendto: no buffer space available

Unable to repro locally with all.bash, so I am assuming it was fluke (resources full).

Running try-bots again.

Patch-set: 10
Reviewer: Gerrit User 15558 <15558@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: Run-TryBot=+1