Update patch set 3
Patch Set 3:

I believe this broke darwin/arm64:

--- FAIL: TestARM64minimalFeatures (0.00s)

	cpu_test.go:55: HasASIMD expected true, got false

FAIL

https://build.golang.org/log/e3670ba882b674e0928d8aa43af9c052e09bce12

Patch-set: 3
CC: Gerrit User 7435 <7435@62eb7196-b449-3ce5-99f1-c037f21e1705>