Update patch set 6
Patch Set 6:

> and then I run all.bat. I think all.bat should complete
 > successfully, but some tests fail:
 > ```
 > ok      io      0.000s
 > ok      io/ioutil       0.000s
 > ok      log     0.000s
 > ok      math    0.000s
 > ok      math/big        0.000s
 > ok      math/cmplx      0.000s
 > ok      math/rand       0.000s
 > ok      mime    0.000s
 > ok      mime/multipart  0.000s
 > ok      mime/quotedprintable    0.000s
 > --- FAIL: TestReadTimeoutFluctuation (0.00s)
 > timeout_test.go:697: unexpected type on 1st nested level:
 > *errors.errorString
 > timeout_test.go:700: Read took 0s; expected 100ms
 > --- FAIL: TestWriteTimeoutFluctuation (0.00s)
 > timeout_test.go:772: unexpected type on 1st nested level:
 > *errors.errorString
 > timeout_test.go:775: Write took 0s; expected 100ms
 > --- FAIL: TestReadFromTimeoutFluctuation (0.00s)
 > ```
 > My PC is Windows 7 (windows/amd64).
 > Don't you think all.bat should pass with my one line change above?

Unfortunately it is not that simple on the real hardware.
Wine has QPC frequency emulated at 10mhz, so every multiplier there is nice and round, while real hardware uses hardware timer which is like 3.3 Ghz or so. And I simply use 
```
	// Since we are supposed to run this time calls only on Wine, it does not lose precision,
	// since Wine's timer is kind of emulated at 10 Mhz, so it will be a nice round multiplier of 100
	// but for general purpose system (like 3.3 Mhz timer on i7) it will not be very precise.
	// We have to do it this way (or similar), since multiplying QPC counter by 100 millions overflows
	// int64 and resulted time will always be invalid.
	qpcMultiplier = int64(timediv(1000000000, qpcFrequency, nil))
```

I could use real hardware frequency here, but it will not be precise because of overflow. I should probably add a runtime panic check if frequency is not 10mhz, or we are ok to be imprecise here?

Patch-set: 6
Reviewer: Gerrit User 17055 <17055@62eb7196-b449-3ce5-99f1-c037f21e1705>