Update patch set 2
Patch Set 2: -Run-TryBot

Ian, I'm seeing a failure in misc/cgo/testshared, can you please advise?

See TryBot output above, failure copied here:

##### ../misc/cgo/testshared
--- FAIL: TestGopathShlib (0.97s)
        shared_test.go:65: executing go install -installsuffix=8674665223082153551 -buildmode=shared -linkshared depBase failed exit status 2:
                # /tmp/go-build144444066/libdepBase.so
                runtime.pclntab: missing section for relocation target syscall.use.args_stackmap
                runtime.pclntab: reloc 1 to non-elf symbol syscall.use.args_stackmap (outer=syscall.use.args_stackmap) 0
                runtime.pclntab: undefined: "syscall.use.args_stackmap"
--- FAIL: TestNotes (0.13s)
        shared_test.go:65: executing go install -installsuffix=8674665223082153551 -buildmode=shared -linkshared depBase failed exit status 2:
                # /tmp/go-build053750199/libdepBase.so
                runtime.pclntab: missing section for relocation target syscall.use.args_stackmap
                runtime.pclntab: reloc 1 to non-elf symbol syscall.use.args_stackmap (outer=syscall.use.args_stackmap) 0
                runtime.pclntab: undefined: "syscall.use.args_stackmap"
--- FAIL: TestTwoGopathShlibs (0.13s)
        shared_test.go:65: executing go install -installsuffix=8674665223082153551 -buildmode=shared -linkshared depBase failed exit status 2:
                # /tmp/go-build865822593/libdepBase.so
                runtime.pclntab: missing section for relocation target syscall.use.args_stackmap
                runtime.pclntab: reloc 1 to non-elf symbol syscall.use.args_stackmap (outer=syscall.use.args_stackmap) 0
                runtime.pclntab: undefined: "syscall.use.args_stackmap"
--- FAIL: TestThreeGopathShlibs (0.14s)
        shared_test.go:65: executing go install -installsuffix=8674665223082153551 -buildmode=shared -linkshared depBase failed exit status 2:
                # /tmp/go-build529321830/libdepBase.so
                runtime.pclntab: missing section for relocation target syscall.use.args_stackmap
                runtime.pclntab: reloc 1 to non-elf symbol syscall.use.args_stackmap (outer=syscall.use.args_stackmap) 0
                runtime.pclntab: undefined: "syscall.use.args_stackmap"
--- FAIL: TestRebuilding (0.12s)
        shared_test.go:65: executing go install -installsuffix=8674665223082153551 -buildmode=shared -linkshared depBase failed exit status 2:
                # /tmp/go-build284663759/libdepBase.so
                runtime.pclntab: missing section for relocation target syscall.use.args_stackmap
                runtime.pclntab: reloc 1 to non-elf symbol syscall.use.args_stackmap (outer=syscall.use.args_stackmap) 0
                runtime.pclntab: undefined: "syscall.use.args_stackmap"
--- FAIL: TestABIChecking (0.13s)
        shared_test.go:65: executing go install -installsuffix=8674665223082153551 -buildmode=shared -linkshared depBase failed exit status 2:
                # /tmp/go-build646840668/libdepBase.so
                runtime.pclntab: missing section for relocation target syscall.use.args_stackmap
                runtime.pclntab: reloc 1 to non-elf symbol syscall.use.args_stackmap (outer=syscall.use.args_stackmap) 0
                runtime.pclntab: undefined: "syscall.use.args_stackmap"
FAIL
exit status 1
FAIL    _/usr/local/google/home/sameer/go/misc/cgo/testshared   8.387s
2017/02/10 09:46:27 Failed: exit status 1

Patch-set: 2
Label: Run-TryBot=0