Update patch set 1
Patch Set 1:

> Patch Set 1: TryBot-Result-1
> 
> 2 of 19 TryBots failed:
> Failed on windows-amd64-2016: https://storage.googleapis.com/go-build-log/c04035be/windows-amd64-2016_ec6a8d9e.log
> Failed on windows-386-2008: https://storage.googleapis.com/go-build-log/c04035be/windows-386-2008_3eed6ffe.log

Looks like tests mostly pass but then:

ok  	cmd/link	6.079s
--- FAIL: TestRuntimeTypeAttrExternal (1.25s)
    dwarf_test.go:1015: DWARF type offset was 0x5480+0x45a040, but test program said 0x30f4c0

So it looks like... ASLR is working as intended?

Patch-set: 1
Reviewer: Gerrit User 20556 <20556@62eb7196-b449-3ce5-99f1-c037f21e1705>