Update patch set 6
Patch Set 6:

I did not look at the code changes properly. But I changed one line:
```
diff --git a/src/runtime/os_windows.go b/src/runtime/os_windows.go
index ced3ce2..174f861 100644
--- a/src/runtime/os_windows.go
+++ b/src/runtime/os_windows.go
@@ -388,7 +388,7 @@ func checkTimers(k32 uintptr) {
                usleep(2)
                t2 := nanotime()
                if t1 != t2 {
-                       return
+                       //return
                }
        }
        _QueryPerformanceCounter = windowsFindfunc(k32, []byte("QueryPerformanceCounter\000"))

```
and then I run all.bat. I think all.bat should complete successfully, but some tests fail:
```
ok      io      0.000s
ok      io/ioutil       0.000s
ok      log     0.000s
ok      math    0.000s
ok      math/big        0.000s
ok      math/cmplx      0.000s
ok      math/rand       0.000s
ok      mime    0.000s
ok      mime/multipart  0.000s
ok      mime/quotedprintable    0.000s
--- FAIL: TestReadTimeoutFluctuation (0.00s)
        timeout_test.go:697: unexpected type on 1st nested level: *errors.errorString
        timeout_test.go:700: Read took 0s; expected 100ms
--- FAIL: TestWriteTimeoutFluctuation (0.00s)
        timeout_test.go:772: unexpected type on 1st nested level: *errors.errorString
        timeout_test.go:775: Write took 0s; expected 100ms
--- FAIL: TestReadFromTimeoutFluctuation (0.00s)
        timeout_test.go:730: unexpected type on 1st nested level: *errors.errorString
        timeout_test.go:733: ReadFrom took 0s; expected 100ms
FAIL
FAIL    net     0.000s
--- FAIL: TestServerTimeouts (0.00s)
        serve_test.go:505: got EOF after 0s, want >= 200ms
FAIL
FAIL    net/http        0.000s
ok      net/http/cgi    0.000s
ok      net/http/cookiejar      0.000s
ok      net/http/fcgi   0.000s
ok      net/http/httptest       0.000s
ok      net/http/httptrace      0.000s
ok      net/http/httputil       0.000s
ok      net/http/internal       0.000s
ok      net/internal/socktest   0.000s
ok      net/mail        0.000s
ok      net/rpc 0.000s
ok      net/rpc/jsonrpc 0.000s
ok      net/smtp        0.000s
ok      net/textproto   0.000s
ok      net/url 0.000s
ok      os      0.000s
ok      os/exec 0.000s
ok      os/signal       0.000s
ok      os/user 0.000s
ok      path    0.000s
ok      path/filepath   0.000s
ok      reflect 0.000s
ok      regexp  0.000s
ok      regexp/syntax   0.000s
--- FAIL: TestCgoCheckBytes (0.00s)
        crash_cgo_test.go:227: cgo check too slow: got 0s, expected at most 0s
FAIL
FAIL    runtime 0.000s
ok      runtime/debug   0.000s
ok      runtime/internal/atomic 0.000s
ok      runtime/internal/sys    0.000s
panic: test timed out after 3m0s

goroutine 36 [running]:
testing.startAlarm.func1()
        c:/Users/Alex/dev/go/src/testing/testing.go:1029 +0x100
created by time.goFunc
        c:/Users/Alex/dev/go/src/time/sleep.go:170 +0x4b

goroutine 1 [chan receive, 2 minutes]:
testing.(*T).Run(0xc04205c1a0, 0x5e252b, 0xe, 0x5ee1c8, 0x47f801)
        c:/Users/Alex/dev/go/src/testing/testing.go:702 +0x310
testing.runTests.func1(0xc04205c1a0)
        c:/Users/Alex/dev/go/src/testing/testing.go:888 +0x6e
testing.tRunner(0xc04205c1a0, 0xc042049e10)
        c:/Users/Alex/dev/go/src/testing/testing.go:659 +0x9f
testing.runTests(0xc0420032a0, 0x6c3700, 0x10, 0x10, 0x410b5c)
        c:/Users/Alex/dev/go/src/testing/testing.go:886 +0x2c8
testing.(*M).Run(0xc042377f20, 0xc04201c000)
        c:/Users/Alex/dev/go/src/testing/testing.go:828 +0x103
main.main()
        runtime/pprof/_test/_testmain.go:78 +0xe2

goroutine 34 [runnable]:
time.Since(0xbe23c88d98878afa, 0x0, 0x6c58a0, 0x0)
        c:/Users/Alex/dev/go/src/time/time.go:882 +0x81
runtime/pprof_test.cpuHogger(0x5ee280, 0xbebc200)
        c:/Users/Alex/dev/go/src/runtime/pprof/pprof_test.go:33 +0x94
runtime/pprof_test.TestCPUProfile.func1(0xbebc200)
        c:/Users/Alex/dev/go/src/runtime/pprof/pprof_test.go:72 +0x3e
runtime/pprof_test.testCPUProfile(0xc04205c270, 0xc042095f88, 0x1, 0x1, 0x5ee198)
        c:/Users/Alex/dev/go/src/runtime/pprof/pprof_test.go:140 +0x124
runtime/pprof_test.TestCPUProfile(0xc04205c270)
        c:/Users/Alex/dev/go/src/runtime/pprof/pprof_test.go:71 +0x72
testing.tRunner(0xc04205c270, 0x5ee1c8)
        c:/Users/Alex/dev/go/src/testing/testing.go:659 +0x9f
created by testing.(*T).Run
        c:/Users/Alex/dev/go/src/testing/testing.go:701 +0x2e6

goroutine 35 [syscall, 2 minutes]:
runtime.CPUProfile(0x5c5d00, 0xc042084000, 0x6c58a0)
        c:/Users/Alex/dev/go/src/runtime/cpuprof.go:448 +0x34
runtime/pprof.profileWriter(0x6ac4e0, 0xc04207f960)
        c:/Users/Alex/dev/go/src/runtime/pprof/pprof.go:708 +0x6c
created by runtime/pprof.StartCPUProfile
        c:/Users/Alex/dev/go/src/runtime/pprof/pprof.go:695 +0x129
FAIL    runtime/pprof   0.000s
ok      runtime/trace   0.000s
ok      sort    0.000s
ok      strconv 0.000s
ok      strings 0.000s
ok      sync    0.000s
ok      sync/atomic     0.000s
ok      syscall 0.000s
panic: test timed out after 3m0s

goroutine 26 [running]:
testing.startAlarm.func1()
        c:/Users/Alex/dev/go/src/testing/testing.go:1029 +0x100
created by time.goFunc
        c:/Users/Alex/dev/go/src/time/sleep.go:170 +0x4b

goroutine 1 [chan receive, 2 minutes]:
testing.(*T).Run(0xc042074340, 0x5a3f84, 0x8, 0x5aff90, 0x487301)
        c:/Users/Alex/dev/go/src/testing/testing.go:702 +0x310
testing.runTests.func1(0xc042074340)
        c:/Users/Alex/dev/go/src/testing/testing.go:888 +0x6e
testing.tRunner(0xc042074340, 0xc042055df8)
        c:/Users/Alex/dev/go/src/testing/testing.go:659 +0x9f
testing.runTests(0xc04203cde0, 0x66dd60, 0x10, 0x10, 0x41079c)
        c:/Users/Alex/dev/go/src/testing/testing.go:886 +0x2c8
testing.(*M).Run(0xc0422a1f20, 0xc04206e780)
        c:/Users/Alex/dev/go/src/testing/testing.go:828 +0x103
testing_test.TestMain(0xc042055f20)
        c:/Users/Alex/dev/go/src/testing/testing_test.go:17 +0x32
main.main()
        testing/_test/_testmain.go:76 +0xe2

goroutine 85 [chan receive, 2 minutes]:
testing.(*B).run1(0xc04205e160, 0xc04205e160)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:222 +0xb3
testing.(*B).Run(0xc04205e000, 0x5a36a7, 0x4, 0xc0421e6c40, 0x0)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:516 +0x20d
testing.TestBRun.func12(0xc04205e000)
        c:/Users/Alex/dev/go/src/testing/sub_test.go:497 +0x5d
testing.(*B).runN(0xc04205e000, 0x1)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:147 +0xb9
testing.TestBRun(0xc04238dad0)
        c:/Users/Alex/dev/go/src/testing/sub_test.go:500 +0x56d
testing.tRunner(0xc04238dad0, 0x5aff90)
        c:/Users/Alex/dev/go/src/testing/testing.go:659 +0x9f
created by testing.(*T).Run
        c:/Users/Alex/dev/go/src/testing/testing.go:701 +0x2e6

goroutine 80 [chan receive (nil chan), 2 minutes]:
testing.(*T).Parallel(0xc04238d520)
        c:/Users/Alex/dev/go/src/testing/testing.go:591 +0x14f
testing.TestTRun.func10(0xc04238d520)
        c:/Users/Alex/dev/go/src/testing/sub_test.go:288 +0x32
testing.tRunner(0xc04238d520, 0x5b0050)
        c:/Users/Alex/dev/go/src/testing/testing.go:659 +0x9f
created by testing.(*T).Run
        c:/Users/Alex/dev/go/src/testing/testing.go:701 +0x2e6

goroutine 86 [chan receive, 2 minutes]:
testing.(*B).doBench(0xc04205e420, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:267 +0xa1
testing.(*B).run(0xc04205e420, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:260 +0xf0
testing.(*B).Run(0xc04205e160, 0x0, 0x0, 0xc04216a000, 0xc042417e00)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:517 +0x285
testing.TestBRun.func2(0xc04205e160)
        c:/Users/Alex/dev/go/src/testing/sub_test.go:388 +0xbd
testing.(*B).runN(0xc04205e160, 0x1)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:147 +0xb9
testing.(*B).run1.func1(0xc04205e160)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:220 +0x61
created by testing.(*B).run1
        c:/Users/Alex/dev/go/src/testing/benchmark.go:213 +0x86

goroutine 88 [sleep]:
time.Sleep(0x1)
        c:/Users/Alex/dev/go/src/runtime/time.go:59 +0x107
testing.TestBRun.func1(0xc04205e420)
        c:/Users/Alex/dev/go/src/testing/sub_test.go:376 +0x49
testing.TestBRun.func2.1(0xc04205e420)
        c:/Users/Alex/dev/go/src/testing/sub_test.go:388 +0x36
testing.(*B).runN(0xc04205e420, 0x1312d00)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:147 +0xb9
testing.(*B).launch(0xc04205e420)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:297 +0x124
created by testing.(*B).doBench
        c:/Users/Alex/dev/go/src/testing/benchmark.go:266 +0x77
FAIL    testing 0.000s
ok      testing/quick   0.000s
ok      text/scanner    0.000s
ok      text/tabwriter  0.000s
ok      text/template   0.000s
ok      text/template/parse     0.000s
--- FAIL: TestHasMonotonicClock (0.00s)
        mono_test.go:16: <-After(1): missing monotonic clock reading
        mono_test.go:16: <-Tick(1): missing monotonic clock reading
        mono_test.go:16: Now(): missing monotonic clock reading
--- FAIL: TestSleep (0.00s)
        sleep_test.go:40: Sleep(100ms) slept for only 0s
--- FAIL: TestAfter (0.00s)
        sleep_test.go:170: After(100ms) slept for only 0 ns
--- FAIL: TestAfterTick (0.00s)
        sleep_test.go:191: 10 ticks of 10ms too fast: took 0s, expected 100ms
--- FAIL: TestAfterQueuing (0.00s)
        sleep_test.go:231: attempt 0 failed: After(20ms) arrived at 0s, expected [10ms,220ms]
        sleep_test.go:231: attempt 1 failed: After(70ms) arrived at 0s, expected [35ms,770ms]
        sleep_test.go:231: attempt 2 failed: After(120ms) arrived at 0s, expected [60ms,1.32s]
        sleep_test.go:231: attempt 3 failed: After(170ms) arrived at 0s, expected [85ms,1.87s]
        sleep_test.go:231: attempt 4 failed: After(220ms) arrived at 0s, expected [110ms,2.42s]
        sleep_test.go:235: After(220ms) arrived at 0s, expected [110ms,2.42s]
--- FAIL: TestTicker (0.00s)
        tick_test.go:26: 10 100ms ticks took 0s, expected [800ms,1.2s]
FAIL
FAIL    time    0.000s
ok      unicode 0.000s
ok      unicode/utf16   0.000s
ok      unicode/utf8    0.000s
ok      vendor/golang_org/x/crypto/chacha20poly1305     0.000s
ok      vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20   0.000s
ok      vendor/golang_org/x/crypto/curve25519   0.000s
ok      vendor/golang_org/x/crypto/poly1305     0.000s
ok      vendor/golang_org/x/net/http2/hpack     0.000s
ok      vendor/golang_org/x/net/idna    0.000s
ok      vendor/golang_org/x/net/lex/httplex     0.000s
ok      cmd/addr2line   0.000s
ok      cmd/api 0.000s
ok      cmd/asm/internal/asm    0.000s
ok      cmd/asm/internal/lex    0.000s
ok      cmd/compile     0.000s
ok      cmd/compile/internal/gc 0.000s
ok      cmd/compile/internal/ssa        0.000s
ok      cmd/compile/internal/syntax     0.000s
ok      cmd/compile/internal/test       0.000s [no tests to run]
ok      cmd/cover       0.000s
ok      cmd/doc 0.000s
ok      cmd/fix 0.000s
ok      cmd/go  0.000s
ok      cmd/go/internal/generate        0.000s
ok      cmd/go/internal/get     0.000s
ok      cmd/go/internal/load    0.000s
ok      cmd/go/internal/work    0.000s
ok      cmd/gofmt       0.000s
ok      cmd/internal/goobj      0.000s
ok      cmd/internal/obj        0.000s
ok      cmd/internal/obj/arm64  0.000s
ok      cmd/internal/obj/x86    0.000s
ok      cmd/internal/src        0.000s
ok      cmd/link        0.000s
ok      cmd/nm  0.000s
ok      cmd/objdump     0.000s
ok      cmd/pack        0.000s
ok      cmd/trace       0.000s
ok      cmd/vendor/golang.org/x/arch/arm/armasm 0.000s
ok      cmd/vendor/golang.org/x/arch/ppc64/ppc64asm     0.000s
ok      cmd/vendor/golang.org/x/arch/x86/x86asm 0.000s
ok      cmd/vet 0.000s
ok      cmd/vet/internal/cfg    0.000s
2017/02/23 20:32:22 Failed: exit status 1

c:\Users\Alex\dev\go\src>
```
My PC is Windows 7 (windows/amd64).
Don't you think all.bat should pass with my one line change above?

Alex

Patch-set: 6
Reviewer: Gerrit User 5070 <5070@62eb7196-b449-3ce5-99f1-c037f21e1705>