Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> Hi Tim. It looks to me as if the dragonfly started failing on the preceding change "
> 
> which seems a little more likely.

This test failure is real. Since this commit, the trace tests started to fail with high probability.

--- FAIL: TestTraceStress (1.74s)
	trace_test.go:147: failed to parse trace: p 2 is running a goroutine 3 during stop (offset 3065, time 674496361)
--- FAIL: TestTraceFutileWakeup (0.13s)
	trace_test.go:147: failed to parse trace: p 4 is not running before stop (offset 73038, time 64316780)

The test failed with the previous commit has been flaky for some time.

I propose rollback and investigate.

Patch-set: 3