Update patch set 3
Patch Set 3:

> I just run all.bat against your change. And it fails with:
 > 
 > --- FAIL: TestEvalSymlinks (0.00s)
 > path_test.go:872: EvalSymlinks(".") in "test/link1" directory
 > returns ".
 > .", want "." or "..\\test"
 > path_test.go:872: EvalSymlinks(".") in "test/link2" directory
 > returns ".
 > .\\dir", want "." or "dir"
 > path_test.go:768: did not find "test/link1/dir" in testDirs slice
 > FAIL
 > FAIL    path/filepath   0.469s
 > 
 > Are you still planning to fix that?
 > 
 > Alex

Sorry, I forgot to test as administrator. I'm in shame.
Yes I'll try to fix if there is no alternative.

Patch-set: 3
Reviewer: Gerrit User 11631 <11631@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: Code-Review=0