Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > > Change the line in gcc_signal_darwin_armx.c from
> > > 
> > > void xx_cgo_panicmem(void);
> > > 
> > > to
> > > 
> > > void xx_cgo_panicmem(void) __attribute__ ((weak));
> > 
> > Just that or delete gcc_signal2_darwin_armx.c as well?
> 
> Sorry for being unclear: delete gcc_signal2_darwin_armx.c, and add the weak attribute so that we don't need it.  Thanks.

Deleting gcc_signal2_darwin_armx.c and adding the weak attribute results in the same error from iostest.sh:

##### Building packages and commands for darwin/arm64.

# runtime/cgo
Undefined symbols for architecture arm64:
  "_xx_cgo_panicmem", referenced from:
      _x_cgo_panicmem in _x007.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
2017/10/08 20:24:02 building mach exception handler: exit status 2

If it's any help, the error comes from the extra build of runtime/cgo in cmd/dist/test.go:

    if t.iOS() {
        // Install the Mach exception handler used to intercept
        // EXC_BAD_ACCESS and convert it into a Go panic. This is
        // necessary for a Go program running under lldb (the way
        // we run tests). It is disabled by default because iOS
        // apps are not allowed to access the exc_server symbol.
        cmd := exec.Command("go", "install", "-a", "-tags", "lldb", "runtime/cgo")
        cmd.Stdout = os.Stdout
        cmd.Stderr = os.Stderr
        if err := cmd.Run(); err != nil {
            log.Fatalf("building mach exception handler: %v", err)
        }

        defer func() {
            cmd := exec.Command("go", "install", "-a", "runtime/cgo")
            cmd.Stdout = os.Stdout
            cmd.Stderr = os.Stderr
            if err := cmd.Run(); err != nil {
                log.Fatalf("reverting mach exception handler: %v", err)
            }
        }()
    }

Patch-set: 1
Reviewer: Gerrit User 7435 <7435@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: Run-TryBot=0