runtime: fix test failed on linx-amd64-noopt
this cl fix test failed on linux-amd64-noopt caused by https://go.dev/cl/427135.

    --- FAIL: TestDebugCallUnsafePoint (0.00s)
        debug_test.go:265: want "call not at safe point", got %!s(<nil>)

Change-Id: Ib24fe27d27baa552b1951729e36789f221d2080e