Update patch set 6
Patch Set 6:

(1 comment)

Hi Martin, I've run some sanitiy tests:

FreeBSD 11.2-BETA3 ARMv7 Allwinner H3 (has AT_HWCAP)
-----------------------------------------------------
  26              ARM.HasIDIVA = isSet(hwcap, hwcap_IDIVA)                      
  (gdb) n  
  internal/cpu.initialize (env="") at /tmp/go/src/internal/cpu/cpu.go:127
  127             processOptions(env)
  (gdb) p 'internal/cpu.ARM'
  $5 = {_ = '\000' <repeats 31 times>, HasIDIVA = true, _ = '\000' <repeats 31 times>}


FreeBSD 11.1-RELEASE ARMv7 Allwinner A20 (doesn't have AT_HWCAP)
----------------------------------------------------------
  26              ARM.HasIDIVA = isSet(hwcap, hwcap_IDIVA)                      
  (gdb) n                                
  internal/cpu.initialize (env="") at /tmp/go/src/internal/cpu/cpu.go:127       
  127             processOptions(env)    
  (gdb) p 'internal/cpu.ARM'                                                                                                                                   
  $4 = {_ = '\000' <repeats 31 times>, HasIDIVA = false, _ = '\000' <repeats 31 times>}   

Which is the desired behavior, as observed before http://golang.org/cl/99780 and http://golang.org/cl/102355.

Note however that when running ./all.bash some x86 tests fail due to missing hwcap_VFP/hwcap_VFP3 constants (they are defined only in os_freebsd_arm.go but
the test invokes a build with an environment set to GOARCH=amd64)

ok      cmd/internal/obj/arm64  0.339s                                                                                    
--- FAIL: TestVexPCrelative (6.24s)                                                                                       
        issue19518_test.go:80: error exit status 2 output # runtime                                                       
                ../go/src/runtime/os_freebsd.go:396:24: undefined: hwcap_VFP                                              
                ../go/src/runtime/os_freebsd.go:399:24: undefined: hwcap_VFP                                              
                ../go/src/runtime/os_freebsd.go:399:34: undefined: hwcap_VFPv3                                            
FAIL                          
FAIL    cmd/internal/obj/x86    6.298s

Patch-set: 6
Reviewer: Gerrit User 5781 <5781@62eb7196-b449-3ce5-99f1-c037f21e1705>