Update patch set 12
Patch Set 12:

> # bootstrap/compress/flate
> /usr/local/go/src/compress/flate/inflate.go:39: undefined: wrapper
> /usr/local/go/src/compress/flate/inflate.go:46: undefined: wrapper

This is because all of the packages listed in cmd/dist/buildtool.go's bootstrapDirs need to still build under Go 1.4.

> How can I bootstrap myself here XD ?

Two general approaches:

1. Move the Unwrap methods in https://go-review.googlesource.com/c/go/+/184818/12/src/compress/flate/inflate.go into a separate file with a build tag like "//+build go1.14", so that it gets ignored with the bootstrap toolchain.

2. Add a wrapper_compat.go file with "//+build !go1.14" and a stub definition like "type wrapper = interface{}" so the methods can compile normally.

Patch-set: 12