Update patch set 5
Patch Set 5:

I think this broke the Mac builder:

##### ../misc/cgo/testcarchive
--- FAIL: TestSignalForwardingExternal (1.16s)
    carchive_test.go:405: program succeeded unexpectedly 20 times
FAIL
2019/04/02 09:51:33 Failed: exit status 1

Patch-set: 5
Reviewer: Gerrit User 5065 <5065@62eb7196-b449-3ce5-99f1-c037f21e1705>