Update patch set 6
Patch Set 6:

I'm slightly confused, as with the changes applied I can't seem to run `./all.bash`. I'm seeing:

johan@johan-x1 ~/gows/src/github.com/johanbrandhorst/go/src $ ./all.bash
Building Go cmd/dist using /usr/local/go/.
Building Go toolchain1 using /usr/local/go/.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for linux/amd64.
# net/http
src/net/http/client.go:307:3: impossible type switch case: rt (type RoundTripper) cannot have dynamic type *Transport (wrong type for RoundTrip method)
        have roundTrip(*Request) (*Response, error)
        want RoundTrip(*Request) (*Response, error)
src/net/http/transport.go:39:5: cannot use Transport literal (type *Transport) as type RoundTripper in assignment:
        *Transport does not implement RoundTripper (missing RoundTrip method)
                have roundTrip(*Request) (*Response, error)
                want RoundTrip(*Request) (*Response, error)
go tool dist: FAILED: /home/johan/gows/src/github.com/johanbrandhorst/go/pkg/tool/linux_amd64/go_bootstrap install -gcflags=all= -ldflags=all= std cmd: exit status 2

Now I think I have correctly defined Transport both in the case of js,wasm and !js,wasm. Am I missing anything obvious?

Patch-set: 6
Reviewer: Gerrit User 16585 <16585@62eb7196-b449-3ce5-99f1-c037f21e1705>