Update patch set 13
Patch Set 13:

(9 comments)

are you still interested in this cl? if so, let's parse pos/neg signs and introduce 32-bit cutoff for not worrying lookupPort.

well, do you usually run "all.bash" or "go test -short std" before uploading new change? #13 set breaks existing tests like the following:

--- FAIL: TestDialError (0.01s)
	error_test.go:166: #8: should fail without operation not supported; tcp:127.0.0.1:123456789->
	error_test.go:166: #10: should fail without operation not supported; udp:127.0.0.1:123456789->
--- FAIL: TestListenError (0.00s)
	error_test.go:258: #7: should fail without operation not supported; tcp:127.0.0.1:123456789->
--- FAIL: TestListenPacketError (0.00s)
	error_test.go:301: #7: should fail; udp:127.0.0.1:52501->
--- FAIL: TestLookupPort (0.01s)
	lookup_test.go:636: LookupPort("tcp", "65536") = 0, <nil>; want 0, error=true
	lookup_test.go:636: LookupPort("udp", "65536") = 0, <nil>; want 0, error=true
	lookup_test.go:636: LookupPort("tcp", "123456789") = 52501, <nil>; want 0, error=true
FAIL

Patch-set: 13
Label: Code-Review=0