Update patch set 1
Patch Set 1: -Run-TryBot

> 8 of 18 TryBots failed:
 > Failed on linux-386: https://storage.googleapis.com/go-build-log/de2a5212/linux-386_967fc123.log
 > Failed on linux-amd64: https://storage.googleapis.com/go-build-log/de2a5212/linux-amd64_a3a17551.log
 > Failed on linux-amd64-race: https://storage.googleapis.com/go-build-log/de2a5212/linux-amd64-race_ffd286cc.log
 > Failed on darwin-amd64-10_11: https://storage.googleapis.com/go-build-log/de2a5212/darwin-amd64-10_11_b151d93a.log
 > Failed on freebsd-amd64-11_1: https://storage.googleapis.com/go-build-log/de2a5212/freebsd-amd64-11_1_e0ee27aa.log
 > Failed on windows-386-2008: https://storage.googleapis.com/go-build-log/de2a5212/windows-386-2008_213937d0.log
 > Failed on openbsd-amd64-62: https://storage.googleapis.com/go-build-log/de2a5212/openbsd-amd64-62_7be9d407.log
 > Failed on windows-amd64-2016: https://storage.googleapis.com/go-build-log/de2a5212/windows-amd64-2016_ab4bd34e.log
 > 
 > Consult https://build.golang.org/ to see whether they are new
 > failures.

You also need to adjust this test:
```
--- FAIL: TestDependencies (0.28s)
	deps_test.go:515: unexpected dependency: os/user imports [internal/syscall/windows/registry]
FAIL
FAIL	go/build	0.349s
```
Alex

Patch-set: 1
Reviewer: Gerrit User 5070 <5070@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: Run-TryBot=0