Update patch set 11
Patch Set 11:

I think this is ready to be reviewed now, if there are no more libc conversions planned for Go 1.11.

Keith, I had to re-add the go:nosplit directives in vlrt.go that you removed in CL 110655. If I don't, nanotime crashes with:

runtime: newstack at runtime.int64div+0x1b0 sp=0x40434f20 stack=[0x40434000, 0x40435000]
	morebuf={pc:0x404d75c sp:0x40434f20 lr:0x0}
	sched={pc:0x4058c00 sp:0x40434f20 lr:0x404d75c ctxt:0x0}
runtime.nanotime(0x0, 0x0)
	/Users/elias/go-tip/src/runtime/sys_darwin.go:141 +0xb4 fp=0x40434f54 sp=0x40434f20 pc=0x404d75c
runtime.notetsleep_internal(0x4247edc, 0x502d1e2f, 0x9, 0x40488460, 0x0, 0x0, 0x40488460)
	/Users/elias/go-tip/src/runtime/lock_sema.go:211 +0x118 fp=0x40434f6c sp=0x40434f54 pc=0x400de44
runtime.notetsleepg(0x4247edc, 0x502d1e2f, 0x9, 0x41a9870)
	/Users/elias/go-tip/src/runtime/lock_sema.go:281 +0x60 fp=0x40434f90 sp=0x40434f6c pc=0x400e1d0
runtime.timerproc(0x4247ec8)
	/Users/elias/go-tip/src/runtime/time.go:261 +0x430 fp=0x40434fe4 sp=0x40434f90 pc=0x404e314
runtime.goexit()
	/Users/elias/go-tip/src/runtime/asm_arm.s:838 +0x4 fp=0x40434fe4 sp=0x40434fe4 pc=0x405d764
created by runtime.(*timersBucket).addtimerLocked
	/Users/elias/go-tip/src/runtime/time.go:160 +0x128
fatal error: runtime: stack split at bad time

runtime stack:
runtime.throw(0x41836fe, 0x20)
	/Users/elias/go-tip/src/runtime/panic.go:589 +0x50 fp=0x4035eea8 sp=0x4035ee94 pc=0x4030a00
runtime.newstack()
	/Users/elias/go-tip/src/runtime/stack.go:904 +0xaa8 fp=0x4035ef74 sp=0x4035eea8 pc=0x4048bc8
runtime.morestack()
	/Users/elias/go-tip/src/runtime/asm_arm.s:416 +0x60 fp=0x4035ef78 sp=0x4035ef74 pc=0x405b9dc

goroutine 19 [syscall]:
runtime.nanotime(0x0, 0x0)
	/Users/elias/go-tip/src/runtime/sys_darwin.go:141 +0xb4 fp=0x40434f54 sp=0x40434f20 pc=0x404d75c
runtime.notetsleep_internal(0x4247edc, 0x502d1e2f, 0x9, 0x40488460, 0x0, 0x0, 0x40488460)
	/Users/elias/go-tip/src/runtime/lock_sema.go:211 +0x118 fp=0x40434f6c sp=0x40434f54 pc=0x400de44
runtime.notetsleepg(0x4247edc, 0x502d1e2f, 0x9, 0x41a9870)
	/Users/elias/go-tip/src/runtime/lock_sema.go:281 +0x60 fp=0x40434f90 sp=0x40434f6c pc=0x400e1d0
runtime.timerproc(0x4247ec8)
	/Users/elias/go-tip/src/runtime/time.go:261 +0x430 fp=0x40434fe4 sp=0x40434f90 pc=0x404e314
runtime.goexit()
	/Users/elias/go-tip/src/runtime/asm_arm.s:838 +0x4 fp=0x40434fe4 sp=0x40434fe4 pc=0x405d764
created by runtime.(*timersBucket).addtimerLocked
	/Users/elias/go-tip/src/runtime/time.go:160 +0x128


What's odd is that the removal of go:nosplit didn't seem to make any difference on darwin/386. GOARCH=386 ./all.bash ran succesfully after adding the directives.

Patch-set: 11
Reviewer: Gerrit User 5206 <5206@62eb7196-b449-3ce5-99f1-c037f21e1705>
Reviewer: Gerrit User 7435 <7435@62eb7196-b449-3ce5-99f1-c037f21e1705>