Update patch set 12
Patch Set 12:

> Patch Set 9: Code-Review+1
> 
> (1 comment)
> 
> Other than that looks good to me. This does not add any additional complexity now.

Seems like removing that line breaks this test in all.bash:

ok  	regexp/syntax	0.524s
--- FAIL: TestGdbAutotmpTypes (0.45s)
    runtime-gdb_test.go:71: gdb version 8.1
    runtime-gdb_test.go:490: could not find []main.astruct; in 'info typrs astruct' output
    runtime-gdb_test.go:491: gdb output:
        Loading Go Runtime support.
        Breakpoint 1 at 0x466960: file /tmp/go-build108604858/main.go, line 8.
--- FAIL: TestGdbBacktrace (0.53s)
    runtime-gdb_test.go:71: gdb version 8.1
    runtime-gdb_test.go:416: could not find '#0.*main\.eee' in backtrace
    runtime-gdb_test.go:417: gdb output:
        Loading Go Runtime support.
        Breakpoint 1 at 0x45cec0: file /tmp/go-build304706812/main.go, line 17.
        warning: linux_test_for_tracefork: unexpected result from waitpid (16418, status 0x1c7f)
--- FAIL: TestGdbPython (0.69s)
    runtime-gdb_test.go:71: gdb version 8.1
    runtime-gdb_test.go:249: gdb output: Loading Go Runtime support.
        Loaded  Script                                                                 
        Yes     /home/dfava/go/go_/src/runtime/runtime-gdb.py                          
        Breakpoint 1 at 0x498865: file /tmp/go-build266664491/main.go, line 16.
        
    runtime-gdb_test.go:278: info goroutines failed: 
FAIL
FAIL	runtime	38.873s

Patch-set: 12