Update patch set 1
Patch Set 1:

If I run this test on my computer, I get this:

=== RUN   TestPanicSystemstack
=== PAUSE TestPanicSystemstack
=== CONT  TestPanicSystemstack
--- FAIL: TestPanicSystemstack (1.11s)
    a_windows_test.go:66: traceback missing user stack:
         Exception 0xbad 0x250fe40 0x0 0x7ffbd0d2a388
        PC=0x7ffbd0d2a388
        
        runtime.cgocall(0x462dd0, 0xc0000342c8, 0x7ffbd2a2c7f0)
        	/home/a/go/src/runtime/cgocall.go:128 +0x55 fp=0xc0000abe80 sp=0xc0000abe48 pc=0x403cf5
        syscall.Syscall6(0x7ffbd2a2c7f0, 0x4, 0xbad, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        	/home/a/go/src/runtime/syscall_windows.go:185 +0xfc fp=0xc0000abeb0 sp=0xc0000abe80 pc=0x44e24c
        syscall.(*Proc).Call(0xc0000b6020, 0xc0000b2020, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0)
        	/home/a/go/src/syscall/dll_windows.go:152 +0x39d fp=0xc0000abf88 sp=0xc0000abeb0 pc=0x47d0ed
        runtime_test.testPanicSystemstackRaiseException()
        	/home/a/go/src/runtime/a_windows_test.go:90 +0xca fp=0xc0000abfe0 sp=0xc0000abf88 pc=0x5ddcda
        runtime.goexit()
        	/home/a/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000abfe8 sp=0xc0000abfe0 pc=0x4615d1
        created by runtime_test.init.0
        	/home/a/go/src/runtime/a_windows_test.go:78 +0xb2
        
        goroutine 1 [running, locked to thread]:
        	goroutine running on other thread; stack unavailable
        
        goroutine 2 [force gc (idle)]:
        runtime.gopark(0x6edee8, 0x8ef140, 0x1410, 0x1)
        	/home/a/go/src/runtime/proc.go:302 +0x100 fp=0xc000025f80 sp=0xc000025f60 pc=0x431f90
        runtime.goparkunlock(0x8ef140, 0x1410, 0x1)
        	/home/a/go/src/runtime/proc.go:308 +0x5a fp=0xc000025fb0 sp=0xc000025f80 pc=0x43204a
        runtime.forcegchelper()
        	/home/a/go/src/runtime/proc.go:251 +0xc1 fp=0xc000025fe0 sp=0xc000025fb0 pc=0x431df1
        runtime.goexit()
        	/home/a/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000025fe8 sp=0xc000025fe0 pc=0x4615d1
        created by runtime.init.4
        	/home/a/go/src/runtime/proc.go:240 +0x3c
        
        goroutine 3 [GC sweep wait]:
        runtime.gopark(0x6edee8, 0x8ef500, 0x42140c, 0x1)
        	/home/a/go/src/runtime/proc.go:302 +0x100 fp=0xc000027f80 sp=0xc000027f60 pc=0x431f90
        runtime.goparkunlock(0x8ef500, 0x72140c, 0x1)
        	/home/a/go/src/runtime/proc.go:308 +0x5a fp=0xc000027fb0 sp=0xc000027f80 pc=0x43204a
        runtime.bgsweep(0xc000014070)
        	/home/a/go/src/runtime/mgcsweep.go:52 +0x9d fp=0xc000027fd8 sp=0xc000027fb0 pc=0x421c8d
        runtime.goexit()
        	/home/a/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000027fe0 sp=0xc000027fd8 pc=0x4615d1
        created by runtime.gcenable
        	/home/a/go/src/runtime/mgc.go:216 +0x5f
        
        goroutine 4 [finalizer wait]:
        runtime.gopark(0x6edee8, 0x910660, 0x50140f, 0x1)
        	/home/a/go/src/runtime/proc.go:302 +0x100 fp=0xc000029f28 sp=0xc000029f08 pc=0x431f90
        runtime.goparkunlock(0x910660, 0x140f, 0x1)
        	/home/a/go/src/runtime/proc.go:308 +0x5a fp=0xc000029f58 sp=0xc000029f28 pc=0x43204a
        runtime.runfinq()
        	/home/a/go/src/runtime/mfinal.go:175 +0xa7 fp=0xc000029fe0 sp=0xc000029f58 pc=0x4192f7
        runtime.goexit()
        	/home/a/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000029fe8 sp=0xc000029fe0 pc=0x4615d1
        created by runtime.createfing
        	/home/a/go/src/runtime/mfinal.go:156 +0x68
        
        goroutine 5 [running]:
        	goroutine running on other thread; stack unavailable
        created by runtime_test.init.0
        	/home/a/go/src/runtime/a_windows_test.go:77 +0x9a
        
        goroutine 18 [timer goroutine (idle)]:
        runtime.gopark(0x6edee8, 0x8f2f60, 0x1414, 0x1)
        	/home/a/go/src/runtime/proc.go:302 +0x100 fp=0xc0000a5f28 sp=0xc0000a5f08 pc=0x431f90
        runtime.goparkunlock(0x8f2f60, 0xc000001414, 0x1)
        	/home/a/go/src/runtime/proc.go:308 +0x5a fp=0xc0000a5f58 sp=0xc0000a5f28 pc=0x43204a
        runtime.timerproc(0x8f2f60)
        	/home/a/go/src/runtime/time.go:280 +0x296 fp=0xc0000a5fd8 sp=0xc0000a5f58 pc=0x44f1b6
        runtime.goexit()
        	/home/a/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000a5fe0 sp=0xc0000a5fd8 pc=0x4615d1
        created by runtime.(*timersBucket).addtimerLocked
        	/home/a/go/src/runtime/time.go:170 +0x11b
        rax     0x7ffbd4663e77
        rbx     0xc0000342c8
        rcx     0xe20000
        rdi     0x2ef000
        rsi     0xc0000abec0
        rbp     0xc0000abe70
        rsp     0x250fd80
        r8      0x7ffbd0a5d901
        r9      0x0
        r10     0x0
        r11     0x1fb590010
        r12     0xffffffffffffffff
        r13     0x2
        r14     0x1
        r15     0x100
        rip     0x7ffbd0d2a388
        rflags  0x202
        cs      0x33
        fs      0x53
        gs      0x2b
        
FAIL

Patch-set: 1
Reviewer: Gerrit User 5070 <5070@62eb7196-b449-3ce5-99f1-c037f21e1705>