Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [golang/try/x_tools-gotip-linux-amd64](https://cr-buildbucket.appspot.com/build/8749118270139545665) has failed with summary ([view all results](https://go-review.googlesource.com/c/582715?checksPatchset=1&tab=checks)):

---
**FAILURE**

* go on master ([change 582715](https://go-review.googlesource.com/c/go/+/582715/1))
* tools on master ([commit 74c9cfe](https://go.googlesource.com/tools/+/74c9cfe4d22faa696baabeea02df6493b15e8c79))

Error: `failed to run "make.bash": exit status 2`

Links:
* ["make.bash" (combined output)](https://logs.chromium.org/logs/golang/buildbucket/cr-buildbucket/8749118270139545665/+/u/step/12/log/2)

Patch-set: 1
Tag: autogenerated:cq:dry-run:1714587631
Attention: {"person_ident":"Gerrit User 10033 \u003c10033@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}