Update patch set 14
Patch Set 14:

Thanks :) This are my changes https://go-review.googlesource.com/c/go/+/184818/14/src/cmd/compile/internal/gc/reflect.go

Not sure about 

dtypesym(types.NewPtr(types.Wrappertype))
dtypesym(functype(nil, []*Node{anonfield(types.Wrappertype)}, []*Node{types.Wrappertype)}))

Maybe that last field need to be a interface like this instead?

dtypesym(functype(nil, []*Node{anonfield(types.Wrappertype)}, []*Node{anonfield(types.Types[TINTER])}))

Anyway tried both and now I past the panic but it seems like I need a other build tag telling that it shouldn't use the first build tag anymore?

gert@gert /usr/local/go/src:#32913> ./all.bash 
Building Go cmd/dist using /usr/local/go1.
Building Go toolchain1 using /usr/local/go1.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
# compress/flate
src/compress/flate/huffman_bit_writer.go:172:9: cannot use InternalError("writeBytes with unfinished bits") (type InternalError) as type error in assignment:
        InternalError does not implement error (wrong type for Unwrap method)
                have Unwrap() interface {}
                want Unwrap() wrapper

Patch-set: 14
Reviewer: Gerrit User 15355 <15355@62eb7196-b449-3ce5-99f1-c037f21e1705>