Update patch set 5
Patch Set 5: Code-Review-1

> Patch Set 5:
> 
> TryBots beginning. Status page: https://farmer.golang.org/try?commit=8575866d

This CL fails non-short tests for me. Still investigating the reason.

--- FAIL: TestConvertLegacyConfig (24.73s)
    --- FAIL: TestConvertLegacyConfig/github.com_docker_distribution_v0.0.0-20150410205453-85de3967aa93 (11.70s)
        convert_test.go:180: final go.mod:
            module github.com/docker/distribution

            require (
                github.com/Sirupsen/logrus v0.7.3
                github.com/bugsnag/bugsnag-go v1.0.3-0.20141110184014-b1d153021fcd
                github.com/bugsnag/osext v0.0.0-20130617224835-0dd3f918b21b
                github.com/bugsnag/panicwrap v0.0.0-20141110184334-e5f9854865b9
                github.com/codegangsta/cli v1.4.2-0.20150131031259-6086d7927ec3
                github.com/docker/libtrust v0.0.0-20150114040149-fa567046d9b1
                github.com/gorilla/context v0.0.0-20140604161150-14f550f51af5
                github.com/gorilla/handlers v0.0.0-20140825150757-0e84b7d810c1
                github.com/gorilla/mux v0.0.0-20140926153814-e444e69cbd2e
                github.com/jlhawn/go-crypto v0.0.0-20150401213827-cd738dde20f0
                github.com/yvasiyarov/go-metrics v0.0.0-20140926110328-57bccd1ccd43
                github.com/yvasiyarov/gorelic v0.0.7-0.20141212073537-a9bba5b9ab50
                github.com/yvasiyarov/newrelic_platform_go v0.0.0-20140908184405-b21fdbd4370f
                gopkg.in/check.v1 v1.0.0-20141024133853-64131543e789
                gopkg.in/yaml.v2 v2.0.0-20150116202057-bef53efd0c76
            )


            want:
            module github.com/docker/distribution

            require (
                github.com/AdRoll/goamz v0.0.0-20150130162828-d3664b76d905
                github.com/MSOpenTech/azure-sdk-for-go v0.0.0-20150323223030-d90753bcad2e
                github.com/Sirupsen/logrus v0.7.3
                github.com/bugsnag/bugsnag-go v1.0.3-0.20141110184014-b1d153021fcd
                github.com/bugsnag/osext v0.0.0-20130617224835-0dd3f918b21b
                github.com/bugsnag/panicwrap v0.0.0-20141110184334-e5f9854865b9
                github.com/codegangsta/cli v1.4.2-0.20150131031259-6086d7927ec3
                github.com/docker/docker v1.4.2-0.20150204013315-165ea5c158cf
                github.com/docker/libtrust v0.0.0-20150114040149-fa567046d9b1
                github.com/garyburd/redigo v0.0.0-20150301180006-535138d7bcd7
                github.com/gorilla/context v0.0.0-20140604161150-14f550f51af5
                github.com/gorilla/handlers v0.0.0-20140825150757-0e84b7d810c1
                github.com/gorilla/mux v0.0.0-20140926153814-e444e69cbd2e
                github.com/jlhawn/go-crypto v0.0.0-20150401213827-cd738dde20f0
                github.com/yvasiyarov/go-metrics v0.0.0-20140926110328-57bccd1ccd43
                github.com/yvasiyarov/gorelic v0.0.7-0.20141212073537-a9bba5b9ab50
                github.com/yvasiyarov/newrelic_platform_go v0.0.0-20140908184405-b21fdbd4370f
                golang.org/x/net v0.0.0-20150202051010-1dfe7915deaf
                gopkg.in/check.v1 v1.0.0-20141024133853-64131543e789
                gopkg.in/yaml.v2 v2.0.0-20150116202057-bef53efd0c76
            )
FAIL
FAIL    cmd/go/internal/modconv 24.911s

Patch-set: 5
Reviewer: Gerrit User 6365 <6365@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: Code-Review=-1