Update patch set 4
Change has been successfully cherry-picked as 3e7cb78800c662b36f9aebf9312ab25b42c2da2a

1 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: doc/godebug.md
Insertions: 4, Deletions: 2.

@@ -168,11 +168,13 @@
 enabled by default on listerners. Using multipathtcp="0" reverts to the
 pre-Go 1.24 behavior.
 
-Go 1.24 changed the behavior of `go test -json` to emit build errors in JSON
+Go 1.24 changed the behavior of `go test -json` to emit build errors as JSON
 instead of text.
 These new JSON events are distinguished by new `Action` values,
 but can still cause problems with CI systems that aren't robust to these events.
-This behavior can be reverted by setting `gotestjsonbuildtext=1`.
+This behavior can be controlled with the `gotestjsonbuildtext` setting.
+Using `gotestjsonbuildtext=1` restores the 1.23 behavior.
+This setting will be removed in a future release, Go 1.28 at the earliest.
 
 ### Go 1.23
 
```
```
The name of the file: src/cmd/go/testdata/script/test_json_build.txt
Insertions: 1, Deletions: 1.

@@ -55,7 +55,7 @@
 env GODEBUG=gotestjsonbuildtext=1
 ! go test -json -o=$devnull ./builderror
 stderr '# m/builderror \[m/builderror.test\]\n'
-stderr 'builderror(/|\\\\)main_test.go:3:11: undefined: y\n'
+stderr 'builderror'${/}'main_test.go:3:11: undefined: y\n'
 stdout '"Action":"start","Package":"m/builderror"'
 stdout '"Action":"output","Package":"m/builderror","Output":"FAIL\\tm/builderror \[build failed\]\\n"'
 stdout '"Action":"fail","Package":"m/builderror","Elapsed":.*,"FailedBuild":"m/builderror \[m/builderror\.test\]"'
```


Patch-set: 4
Subject: cmd/go: re-enable build JSON from go test -json, now with GODEBUG
Status: merged
Commit: 3e7cb78800c662b36f9aebf9312ab25b42c2da2a
Tag: autogenerated:gerrit:merged
Groups: bf668c9ed067a8df9b49a1fc93b19d8827f849c1
Label: Code-Review=+2, e283b6ab25162892ecb0cacb3878c51f25d10ec2 Gerrit User 6005 <6005@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: Code-Review=+1, fdf4c900aa1ef0bca9405814900fad555d03e84a Gerrit User 35155 <35155@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: LUCI-TryBot-Result=+1, 2d9813f148c51e8398a75b61bd4c0f498bb87bcc Gerrit User 60063 <60063@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: Auto-Submit=+1, 99724dda1db5791659caba61b623fe18c6bb847f Gerrit User 5167 <5167@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: Commit-Queue=0, 6b9ebb5610254addd042a4eaa8653e1760ade885 Gerrit User 5167 <5167@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: SUBM=+1, 1bfb818c91e13efb859af639ba233a65acedf24f
Submission-id: 629335
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Code-Review: Gerrit User 35155 <35155@62eb7196-b449-3ce5-99f1-c037f21e1705>
Submitted-with: MAY: Hold
Submitted-with: MAY: Run-TryBot
Submitted-with: MAY: TryBot-Result
Submitted-with: MAY: LUCI-TryBot-Result: Gerrit User 60063 <60063@62eb7196-b449-3ce5-99f1-c037f21e1705>
Submitted-with: MAY: Auto-Submit: Gerrit User 5167 <5167@62eb7196-b449-3ce5-99f1-c037f21e1705>
Submitted-with: MAY: TryBot-Bypass
Submitted-with: MAY: Bot-Commit
Submitted-with: MAY: Commit-Queue
Attention: {"person_ident":"Gerrit User 25391 \u003c25391@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 13315 \u003c13315@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"REMOVE","reason":"Change was submitted"}