Update patch set 2
Patch Set 2:

Also had a failure in the overnight run, which also was undertesting because I forgot to 'go clean -cache' between iterations.  Perhaps it was caused by that typo -- will try again with the fix, aimed at the failure case (in runtime): 

--- FAIL: TestCgoCallbackGC (60.01s)
    crash_test.go:95: testprogcgo CgoCallbackGC exit status: exit status 2
    crash_cgo_test.go:70: expected "OK\n", but got:
        SIGQUIT: quit
        PC=0x7fe67367a4b6 m=0 sigcode=0
        
        goroutine 0 [idle]:
        runtime: unknown pc 0x7fe67367a4b6
        stack: frame={sp:0x7ffe4da95860, fp:0x0} stack=[0x7ffe4d296988,0x7ffe4da959c0)
        00007ffe4da95760:  0000000000000000  0000000000000000 
        00007ffe4da95770:  0000000000000000  0000000000000000 
        00007ffe4da95780:  0000000000000000  0000000000000000 
        00007ffe4da95790:  0000000000000000  0000000000000000 
        00007ffe4da957a0:  0000000000000000  0000000000000000 
        00007ffe4da957b0:  0000000000000000  0000000000000000 
        00007ffe4da957c0:  0000000000000000  0000000000000000 
        00007ffe4da957d0:  0000000000000000  0000000000000000 
        00007ffe4da957e0:  0000000000000000  0000000000000000 
        00007ffe4da957f0:  0000000000000000  0000000000000000 
        00007ffe4da95800:  0000000000000000  0000000000000000 
        00007ffe4da95810:  0000000000000000  0000000000000000 
        00007ffe4da95820:  0000000000000000  0000000000000000 
        00007ffe4da95830:  0000000000000000  0000000000000000 
        00007ffe4da95840:  0000000000000000  0000000000000000 
        00007ffe4da95850:  0000000000000000  00007fe67367a4a5 
        00007ffe4da95860: <00007fe67367a310  00007fe64a7f7d28 
        00007ffe4da95870:  0000000000000000  0000000000000000 
        00007ffe4da95880:  00000000004550e5 <runtime.funcname+69>  9fc4d36c2ff33600 
        00007ffe4da95890:  0000000000000018  000000c0000c7fb8 
        00007ffe4da958a0:  00007ffe4da95910  0000000000000003 
        00007ffe4da958b0:  0000000000000008  000080c000160000 
        00007ffe4da958c0:  000080c0001dffff  00000000004de7fd 
        00007ffe4da958d0:  0000000000000000  0000000000000000 
        00007ffe4da958e0:  0000000000001000  0000000000000000 
        00007ffe4da958f0:  0000000000040000  0000000000000000 
        00007ffe4da95900:  0000000000000000  00007fe64a7f7700 
        00007ffe4da95910:  00007ffe4da95940  00000000004de81e 
        00007ffe4da95920:  000100c0000c7fd8  000000c0000c7fb8 
        00007ffe4da95930:  000000c0000b5680  000000c0000c7fb8 
        00007ffe4da95940:  000000c0000c7f78  000000000046ac50 <runtime.asmcgocall+112> 
        00007ffe4da95950:  00007ffe4da95980  000000000043f9bd <runtime.park_m+157>

Patch-set: 2
Reviewer: Gerrit User 7061 <7061@62eb7196-b449-3ce5-99f1-c037f21e1705>