cmd/go: disambiguate for-test packages in failure output
Now that we can tell when a package is a split-off copy
for testing, show that in the build failures.
For example, instead of:

	# regexp/syntax
	../../regexp/syntax/parse.go:9:2: can't find import: "strings"
	# path/filepath
	../../path/filepath/match.go:12:2: can't find import: "strings"
	# flag
	../../flag/flag.go:75:2: can't find import: "strings"

we now print

	# regexp/syntax [strings.test]
	../../regexp/syntax/parse.go:9:2: can't find import: "strings"
	# path/filepath [strings.test]
	../../path/filepath/match.go:12:2: can't find import: "strings"
	# flag [strings.test]
	../../flag/flag.go:75:2: can't find import: "strings"

which gives more of a hint about what is wrong.

This is especially helpful if a package is being built multiple times,
since it explains why an error might appear multiple times:

	$ go test regexp encoding/json
	# regexp
	../../regexp/exec.go:12:9: undefined: x
	# regexp [regexp.test]
	../../regexp/exec.go:12:9: undefined: x
	FAIL	regexp [build failed]
	FAIL	encoding/json [build failed]
	$

Change-Id: Ie325796f6c3cf0e23f306066be8e65a30cb6b939