Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> Sorry I never looked at this before.  This seems much more complex than is necessary.  The map assignment is always going to copy the value.  So you should be able to do
>     kv := reflect.New(mtyp.Key())
>     kz := reflect.Zero(mtyp.Key())
>     for i := 0; i < n; i++ {
>         key := decodeIntoValue(..., kv.Elem(), ...)
>         kv.Elem().Set(kz)
>     }
> At least, I don't see why that wouldn't work for every type.

This approach fails in tests:

func (dec *Decoder) decodeMap(mtyp reflect.Type, state *decoderState, value reflect.Value, keyOp, elemOp decOp, ovfl error) {
	n := int(state.decodeUint())
	if value.IsNil() {
		value.Set(reflect.MakeMapWithSize(mtyp, n))
	}
	keyIsPtr := mtyp.Key().Kind() == reflect.Ptr
	elemIsPtr := mtyp.Elem().Kind() == reflect.Ptr
	keyInstr := &decInstr{keyOp, 0, nil, ovfl}
	elemInstr := &decInstr{elemOp, 0, nil, ovfl}
	key := reflect.New(mtyp.Key())
	keyZ := reflect.Zero(mtyp.Key())
	elem := reflect.New(mtyp.Elem())
	elemZ :=  reflect.Zero(mtyp.Elem())
	for i := 0; i < n; i++ {
		key = decodeIntoValue(state, keyOp, keyIsPtr, key.Elem(), keyInstr)
		elem = decodeIntoValue(state, elemOp, elemIsPtr, elem.Elem(), elemInstr)
		value.SetMapIndex(key, elem)
		key.Elem().Set(keyZ)
		elem.Elem().Set(elemZ)
	}
}


--- FAIL: TestEndToEnd (0.00s)
panic: reflect: call of reflect.Value.Elem on string Value [recovered]
	panic: reflect: call of reflect.Value.Elem on string Value [recovered]
	panic: reflect: call of reflect.Value.Elem on string Value

goroutine 10 [running]:
testing.tRunner.func1(0xc4200ae4b0)
	/Users/gruszczy/Projects/golang/src/testing/testing.go:712 +0x2dc
panic(0x11a2700, 0xc4200dc820)
	/Users/gruszczy/Projects/golang/src/runtime/panic.go:489 +0x25a
encoding/gob.catchError(0xc4200b03f0)
	/Users/gruszczy/Projects/golang/src/encoding/gob/error.go:38 +0x9f
panic(0x11a2700, 0xc4200dc820)
	/Users/gruszczy/Projects/golang/src/runtime/panic.go:489 +0x25a
reflect.Value.Elem(0x1196a20, 0xc420049b90, 0x198, 0x1196a20, 0xc420049b90, 0x198)
	/Users/gruszczy/Projects/golang/src/reflect/value.go:752 +0x1c6
encoding/gob.(*Decoder).decodeMap(0xc4200b0380, 0x12b53c0, 0x11a4500, 0xc4200dc320, 0x11a4500, 0xc4200b8158, 0x195, 0x11e5c40, 0x11e5bb8, 0x12b0780, ...)
	/Users/gruszczy/Projects/golang/src/encoding/gob/decode.go:590 +0x568
encoding/gob.(*Decoder).decOpFor.func2(0xc4200b24a8, 0xc4200dc320, 0x11a4500, 0xc4200b8158, 0x195)
	/Users/gruszczy/Projects/golang/src/encoding/gob/decode.go:843 +0x97
encoding/gob.(*Decoder).decodeStruct(0xc4200b0380, 0xc4200dc760, 0x11d0b00, 0xc4200b8140, 0x199)
	/Users/gruszczy/Projects/golang/src/encoding/gob/decode.go:471 +0xdc
encoding/gob.(*Decoder).decodeValue(0xc4200b0380, 0x41, 0x11d0b00, 0xc4200b8140, 0x199)
	/Users/gruszczy/Projects/golang/src/encoding/gob/decode.go:1217 +0x28f
encoding/gob.(*Decoder).DecodeValue(0xc4200b0380, 0x118bae0, 0xc4200b8140, 0x16, 0x0, 0x0)
	/Users/gruszczy/Projects/golang/src/encoding/gob/decoder.go:210 +0x145
encoding/gob.(*Decoder).Decode(0xc4200b0380, 0x118bae0, 0xc4200b8140, 0xc420018cb0, 0x9)
	/Users/gruszczy/Projects/golang/src/encoding/gob/decoder.go:185 +0x16d
encoding/gob.TestEndToEnd(0xc4200ae4b0)
	/Users/gruszczy/Projects/golang/src/encoding/gob/codec_test.go:614 +0xdb8
testing.tRunner(0xc4200ae4b0, 0x11e58f0)
	/Users/gruszczy/Projects/golang/src/testing/testing.go:747 +0xd0
created by testing.(*T).Run
	/Users/gruszczy/Projects/golang/src/testing/testing.go:789 +0x2de

At the bottom of the decode.go is allocation function that I believe addresses that with a comment:

// Gob depends on being able to take the address
// of zeroed Values it creates, so use this wrapper instead
// of the standard reflect.Zero.
// Each call allocates once.
func allocValue(t reflect.Type) reflect.Value {
	return reflect.New(t).Elem()
}


Let me try to explain my understanding of why the different behavior is needed with pointers. I think the reason is shallow copying into the map.

We start with:
tempValue --- Pointer ---> internal value

Copy tempValue to the map:

tempValue -- Pointer ---> internal value
map entry -- Pointer ----------^


Reuse tempValue to decode another element

tempValue -- Pointer ---> new internal value
map entry -- Pointer --------^


That's why I add all the new tests to this CL, they tackle this behavior. Even before I added them there was fortunately already one that was catching it. That's how I came to this convoluted solution.

Patch-set: 3
Reviewer: Gerrit User 17532 <17532@62eb7196-b449-3ce5-99f1-c037f21e1705>