Update patch set 8
Patch Set 8:

> I am afraid that we've entered "perfect is the enemy of good"
 > territory here. Can we please get something Snappy-like in as gzip
 > -1 for Go 1.7? It's okay if it gets even better for Go 1.8. Thanks.

Very well, I've just mailed out https://go-review.googlesource.com/#/c/22370/ which does exactly that, including some new tests for level == BestSpeed.



Klaus, if you want authorship attribution, you are welcome to copy/paste that into a new CL and send that out to Russ, but time is of the essence.

I tried to change the Author on cl/22370 to be you (Klaus), but "git codereview mail" did not like it:

$ git codereview mail -r rsc -cc klauspost@gmail.com
remote: Processing changes: refs: 1, done
remote:
remote: ERROR:  In commit 519dec7785505b160df09bdb343abaad5aacb7b0
remote: ERROR:  author email address klauspost@gmail.com
remote: ERROR:  does not match your user account.
remote: ERROR:
remote: ERROR:  The following addresses are currently registered:
remote: ERROR:    nigeltao@golang.org
remote: ERROR:
remote: ERROR:  To register an email address, please visit:
remote: ERROR:  https://go-review.googlesource.com/#/settings/contact
remote:
remote:
To https://go.googlesource.com/go
 ! [remote rejected] HEAD ->
refs/for/master%r=rsc@golang.org,cc=klauspost@gmail.com (invalid
author)
error: failed to push some refs to 'https://go.googlesource.com/go'
(running: git push -q origin
HEAD:refs/for/master%r=rsc@golang.org,cc=klauspost@gmail.com)
git-codereview: exit status 1



$ git log|head
commit 519dec7785505b160df09bdb343abaad5aacb7b0
Author: Klaus Post <klauspost@gmail.com>
Date:   Tue Apr 26 12:56:17 2016 +1000

    compress/flate: replace "Best Speed" with specialized version

    This encoding algorithm, which prioritizes speed over output size, is
    based on Snappy's LZ77-style encoder: github.com/golang/snappy

    This commit keeps the diff between this package's encodeBestSpeed

Patch-set: 8
Reviewer: Gerrit User 5899 <5899@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: Code-Review=0