cmd/dist: add maymorestack tests
These tests run the runtime, reflect, and sync package tests with the
two maymorestack hooks we have.

These tests only run on the longtest builders (or with
GO_TEST_SHORT=false) because they are rather slow. To run just these
tests, do

  GO_TEST_SHORT=false go tool dist test -run mayMoreStack

Updates #48297.

DO NOT SUBMIT. Once bugs are fixed, check how long these actually
take.

DO NOT SUBMIT. There are at least two real test failures right now:

1. There's a reentrancy issue with stack growth during allocation.
This should be fixed by CL 361158.

2. TestTracebackArgs fails if there's a preemption between poisoning
the argument area and calling the test function because (I think) this
forces the register arguments to spill, thus "unpoisoning" the stack.
For example,

--- FAIL: TestTracebackArgs (0.00s)
    traceback_test.go:175: traceback does not contain expected string: want "testTracebackArgs9(0x1, 0xffffffff?, 0x3, 0xff?, {0x5, 0x6}, 0x7)", got
        goroutine 165151 [running]:
        runtime_test.testTracebackArgs9(0x1, 0x2?, 0x3, 0x4?, {0x5, 0x6}, 0x7)
        	/home/austin/go.dev/src/runtime/traceback_test.go:361 +0x8f
        runtime_test.TestTracebackArgs.func17()
        	/home/austin/go.dev/src/runtime/traceback_test.go:131 +0x5b
        runtime_test.TestTracebackArgs(0xc00007e000)
        	/home/austin/go.dev/src/runtime/traceback_test.go:172 +0x30f
        testing.tRunner(0xc00007e000, 0x67beb0)
        	/home/austin/go.dev/src/testing/testing.go:1409 +0x102
        created by testing.(*T).Run
        	/home/austin/go.dev/src/testing/testing.go:1456 +0x35f

Change-Id: If785a8b8d6e1b9ad4d2ae67493b54055ab6cbc85