Update patch set 3
Patch Set 3:

This CL has failed the run. Reason:

Tryjob [golang/try/x_tools-gotip-linux-amd64](https://cr-buildbucket.appspot.com/build/8765426245344484353) has failed with summary [(view all results)](https://go-review.googlesource.com/c/538535?checksPatchset=3&tab=checks):

---
**FAILURE**

* go on master ([change 538535](https://go-review.googlesource.com/c/go/+/538535/3))
* tools on master ([commit 08edf75](https://go.googlesource.com/tools/+/08edf75c4df409a46133447c4ad0a4cde62d6a73))

error: failed to run "test golang.org/x/tools module": exit status 1
* ["test golang.org/x/tools module" (combined output)](https://logs.chromium.org/logs/golang/buildbucket/cr-buildbucket/8765426245344484353/+/u/step/25/log/2)

Patch-set: 3
Tag: autogenerated:cq:dry-run:1699035133
Attention: {"person_ident":"Gerrit User 5200 \u003c5200@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"ADD","reason":"ps#3: Tryjobs failed"}