Update patch set 10
Patch Set 10:

> Patch Set 10:
> 
> TestExitCode is failing on Plan 9.

This is the failure mode:

```
flag provided but not defined: -x
flag needs an argument: -b
Usage of test:
  -b	usage
--- FAIL: TestExitCode (0.06s)
    flag_test.go:603: unexpected exit code for test case {flag:-undefined flagHandle: expectExit:2} 
        : got 1, expect 2
    flag_test.go:603: unexpected exit code for test case {flag:-h flagHandle:h expectExit:123} 
        : got 1, expect 123
    flag_test.go:603: unexpected exit code for test case {flag:-help flagHandle:help expectExit:123} 
        : got 1, expect 123
FAIL
FAIL	flag	0.094s
```

Is it possible that the `os` package on Plan 9 does not report exit codes?

Patch-set: 10
CC: Gerrit User 6365 <6365@62eb7196-b449-3ce5-99f1-c037f21e1705>