Update patch set 7
Patch Set 7:

Reverted this CL - it broke all the dashboard builds.

--- FAIL: TestQueryExecContextOnly (0.00s)
	sql_test.go:3608: exec create session is dirty
FAIL
FAIL	database/sql	0.605s

Patch-set: 7
CC: Gerrit User 5056 <5056@62eb7196-b449-3ce5-99f1-c037f21e1705>