Update patch set 6
Patch Set 6:

I tried to do this a while back, and it didn't work under certain conditions, so we had to roll it back. I am slightly afraid this CL will fall to the same problems. In particular, I suspect this CL is the root cause for this trybot failure:
https://storage.googleapis.com/go-build-log/3edb6fc2/linux-amd64-race_0b92a3c7.log

ok  	runtime/debug	1.027s
runtime: invalid pc-encoded table f=type..eq.internal/singleflight.Result pc=0x61fb90 targetpc=0x622bb0 tab=[0/0]0x0
	value=0 until pc=0x61f9aa
	value=104 until pc=0x61fb39
	value=0 until pc=0x61fb3a
	value=104 until pc=0x61fb4b
	value=0 until pc=0x61fb4c
	value=104 until pc=0x61fb5d
	value=0 until pc=0x61fb5e
	value=104 until pc=0x61fb7d
	value=0 until pc=0x61fb7e
	value=104 until pc=0x61fb90
fatal error: invalid runtime symbol table

goroutine 0 [idle]:
runtime.throw(0x73e1d0, 0x1c)
	/tmp/buildlet-scatch123172301/go/src/runtime/panic.go:527 +0x96
runtime.pcvalue(0x8330c0, 0xaa587, 0x622bb0, 0x10740042b001, 0xf)
	/tmp/buildlet-scatch123172301/go/src/runtime/symtab.go:221 +0x385
runtime.funcspdelta(0x8330c0, 0x622bb0, 0x43deb0)
	/tmp/buildlet-scatch123172301/go/src/runtime/symtab.go:254 +0x3e
runtime.gentraceback(0x622bb0, 0x7ff47784eab0, 0x0, 0xc208000b40, 0x0, 0xc2080517a8, 0x40, 0x0, 0x0, 0x6, ...)
	/tmp/buildlet-scatch123172301/go/src/runtime/traceback.go:211 +0x357
runtime.sigprof(0x622bb0, 0x7ff47784eab0, 0x0, 0xc208000b40, 0xc208028800)
	/tmp/buildlet-scatch123172301/go/src/runtime/proc1.go:2562 +0x413
runtime.sighandler(0xc20000001b, 0xc208051bf0, 0xc208051ac0, 0xc208000b40)
	/tmp/buildlet-scatch123172301/go/src/runtime/signal_amd64x.go:47 +0xd2
runtime.sigtrampgo(0x1b, 0xc208051bf0, 0xc208051ac0)
	/tmp/buildlet-scatch123172301/go/src/runtime/signal_linux.go:94 +0x98
runtime.sigtramp(0x1, 0x0, 0xc20804a000, 0x0, 0x8000, 0xffffffffffffffff, 0x0, 0x4032, 0x206, 0x0, ...)
	/tmp/buildlet-scatch123172301/go/src/runtime/sys_linux_amd64.s:228 +0x1b
runtime.sigreturn(0x0, 0xc20804a000, 0x0, 0x8000, 0xffffffffffffffff, 0x0, 0x4032, 0x206, 0x0, 0xc210500000, ...)
	/tmp/buildlet-scatch123172301/go/src/runtime/sys_linux_amd64.s:232

goroutine 30 [running]:
runtime.systemstack_switch()
	/tmp/buildlet-scatch123172301/go/src/runtime/asm_amd64.s:216 fp=0xc208039b28 sp=0xc208039b20
runtime.mallocgc(0x20, 0x6b6500, 0x0, 0x45a474)
	/tmp/buildlet-scatch123172301/go/src/runtime/malloc.go:606 +0x788 fp=0xc208039c08 sp=0xc208039b28
runtime.newobject(0x6b6500, 0x24baf15fe1658f99)
	/tmp/buildlet-scatch123172301/go/src/runtime/malloc.go:728 +0x49 fp=0xc208039c30 sp=0xc208039c08
math/big.NewInt(0xbb10cb777fb8137, 0xc2103fbfe0)
	/tmp/buildlet-scatch123172301/go/src/math/big/int.go:62 +0x38 fp=0xc208039c50 sp=0xc208039c30
runtime/pprof_test.TestMathBigDivide.func1()
	/tmp/buildlet-scatch123172301/go/src/runtime/pprof/pprof_test.go:312 +0xa1 fp=0xc208039cb8 sp=0xc208039c50
runtime/pprof_test.testCPUProfile(0xc20806e6c0, 0x0, 0x0, 0x0, 0xc208039f70)
	/tmp/buildlet-scatch123172301/go/src/runtime/pprof/pprof_test.go:144 +0x1cf fp=0xc208039f48 sp=0xc208039cb8
runtime/pprof_test.TestMathBigDivide(0xc20806e6c0)
	/tmp/buildlet-scatch123172301/go/src/runtime/pprof/pprof_test.go:321 +0x6e fp=0xc208039f88 sp=0xc208039f48
testing.tRunner(0xc20806e6c0, 0x84f5b8)
	/tmp/buildlet-scatch123172301/go/src/testing/testing.go:454 +0xfc fp=0xc208039fd0 sp=0xc208039f88
runtime.goexit()
	/tmp/buildlet-scatch123172301/go/src/runtime/asm_amd64.s:1670 +0x1 fp=0xc208039fd8 sp=0xc208039fd0
created by testing.RunTests
	/tmp/buildlet-scatch123172301/go/src/testing/testing.go:562 +0xc96

goroutine 1 [chan receive]:
testing.RunTests(0x777f70, 0x84f540, 0xe, 0xe, 0x1)
	/tmp/buildlet-scatch123172301/go/src/testing/testing.go:563 +0xcec
testing.(*M).Run(0xc2084bbf40, 0x77a3e0)
	/tmp/buildlet-scatch123172301/go/src/testing/testing.go:492 +0xe8
main.main()
	runtime/pprof/_test/_testmain.go:82 +0x213

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/tmp/buildlet-scatch123172301/go/src/runtime/asm_amd64.s:1670 +0x1

goroutine 31 [syscall]:
runtime.CPUProfile(0x0, 0x0, 0x0)
	/tmp/buildlet-scatch123172301/go/src/runtime/cpuprof.go:418 +0x3b
runtime/pprof.profileWriter(0x7ff47786d450, 0xc208052620)
	/tmp/buildlet-scatch123172301/go/src/runtime/pprof/pprof.go:594 +0x2d
created by runtime/pprof.StartCPUProfile
	/tmp/buildlet-scatch123172301/go/src/runtime/pprof/pprof.go:588 +0x1bf
FAIL	runtime/pprof	5.093s

Patch-set: 6