Update patch set 18
Patch Set 18:

Copied the wrong output the `does not implement error (missing Unwrap method)` I can fix, it's the `could not import X (cannot import "X" (predeclared type missing from cache: 30), possibly version skew - reinstall package)`

gert@gert /usr/local/go/src:#32913> ./all.bash 
Building Go cmd/dist using /usr/local/go1.
Building Go toolchain1 using /usr/local/go1.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for darwin/amd64.

##### Testing packages.
# io
vet: io/io.go:16:2: could not import errors (cannot import "errors" (predeclared type missing from cache: 30), possibly version skew - reinstall package)
# internal/oserror
vet: internal/oserror/errors.go:10:8: could not import errors (cannot import "errors" (predeclared type missing from cache: 30), possibly version skew - reinstall package)
# strconv
vet: strconv/atoi.go:7:8: could not import errors (cannot import "errors" (predeclared type missing from cache: 30), possibly version skew - reinstall package)
# bytes
vet: bytes/buffer.go:10:2: could not import errors (cannot import "errors" (predeclared type missing from cache: 30), possibly version skew - reinstall package)
# strings
vet: strings/reader.go:8:2: could not import errors (cannot import "errors" (predeclared type missing from cache: 30), possibly version skew - reinstall package)
# crypto
vet: crypto/crypto.go:11:2: could not import strconv (cannot import "strconv" (predeclared type missing from cache: 30), possibly version skew - reinstall package)
...

Patch-set: 18
Reviewer: Gerrit User 15355 <15355@62eb7196-b449-3ce5-99f1-c037f21e1705>