Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> I believe this broke darwin/arm64:
> 
> --- FAIL: TestARM64minimalFeatures (0.00s)
> 
> 	cpu_test.go:55: HasASIMD expected true, got false
> 
> FAIL
> 
> https://build.golang.org/log/e3670ba882b674e0928d8aa43af9c052e09bce12

Is darwin/arm64 not a standard ARMv8?
I implement this test according to this document.

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.den0024a/CJHECGIH.html

Both floating-point and NEON are required in all standard ARMv8 implementations.

Patch-set: 3
Reviewer: Gerrit User 7530 <7530@62eb7196-b449-3ce5-99f1-c037f21e1705>