Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> I believe TestTransportEventTrace_h2 should also be fixed to guarantee we do not log a GotConn for h2.

I don't think an explicit test is needed, because TestTransportEventTrace_h2 already fails if the other w.pc.alt == nil check is missing.

--- FAIL: TestTransportEventTrace_h2 (0.00s)
    transport_test.go:4289: expected substring "got conn: {" exactly once in output.
    transport_test.go:4326: Output:
        Getting conn for dns-is-faked.golang:36209 ...
        DNS start: {Host:dns-is-faked.golang}
        DNS done: {Addrs:[{IP:127.0.0.1 Zone:}] Err:<nil> Coalesced:false}
        ConnectStart: Connecting to tcp 127.0.0.1:36209 ...
        ConnectDone: connected to tcp 127.0.0.1:36209 = <nil>
        tls handshake start
        tls handshake done. ConnectionState = {772 true false 4865 h2 true  [0xc000434b00] [] [] [] 0x691940 []} 
         err = <nil>
        got conn: {Conn:<nil> Reused:true WasIdle:false IdleTime:0s}
        got conn: {Conn:0xc000452000 Reused:false WasIdle:false IdleTime:0s}

Patch-set: 3
Reviewer: Gerrit User 20190 <20190@62eb7196-b449-3ce5-99f1-c037f21e1705>