Update patch set 6
Patch Set 6:

This CL has failed the run. Reason:

Tryjob [golang/try/x_tools-gotip-linux-amd64](https://cr-buildbucket.appspot.com/build/8766076382738414081) has failed with summary [(view all results)](https://go-review.googlesource.com/c/529116?checksPatchset=6&tab=checks):

---
**FAILURE**

* go on master ([change 529116](https://go-review.googlesource.com/c/go/+/529116/6))
* tools on master ([commit 50cdf2a](https://go.googlesource.com/tools/+/50cdf2a811b1d9a92aba634081ce65f094f7bd89))

error: failed to run "test golang.org/x/tools module": exit status 1
* ["test golang.org/x/tools module" (combined output)](https://logs.chromium.org/logs/golang/buildbucket/cr-buildbucket/8766076382738414081/+/u/step/25/log/2)

Patch-set: 6
Tag: autogenerated:cq:dry-run:1698415112
Attention: {"person_ident":"Gerrit User 14020 \u003c14020@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"ADD","reason":"ps#6: Tryjobs failed"}