Update patch set 11
Patch Set 11:

(3 comments)

Yeea I think it's looking good, going to try to fix all, does not implement error (missing Unwrap method) messages :) Hopefully there are not so many. Only have a few at the moment.

/usr/local/go/src/internal/oserror/errors.go:35:10: invalid operation: err == ErrTimeout (mismatched types error and timeoutError)
/usr/local/go/src/internal/oserror/errors.go:41:60: cannot use ErrTimeout (type timeoutError) as type error in argument to x.Is:
        timeoutError does not implement error (missing Unwrap method)
/usr/local/go/src/internal/oserror/errors.go:52:10: invalid operation: err == ErrTemporary (mismatched types error and temporaryError)
/usr/local/go/src/internal/oserror/errors.go:58:60: cannot use ErrTemporary (type temporaryError) as type error in argument to x.Is:
        temporaryError does not implement error (missing Unwrap method)

Patch-set: 11
Reviewer: Gerrit User 15355 <15355@62eb7196-b449-3ce5-99f1-c037f21e1705>