Update patch set 2
Patch Set 2:

and other breaks on 32-bit platforms. 

--- FAIL: TestDialError (0.14s)
	error_test.go:163: #8: should fail without operation not supported; tcp:127.0.0.1:123456789->
	error_test.go:163: #10: should fail without operation not supported; udp:127.0.0.1:123456789->
--- FAIL: TestListenError (0.00s)
	error_test.go:255: #7: should fail without operation not supported; tcp:127.0.0.1:123456789->
--- FAIL: TestListenPacketError (0.00s)
	error_test.go:298: #7: should fail; udp:127.0.0.1:52501->

Patch-set: 2
Label: Code-Review=0