cmd/compile/types2: add position failed failed interface satisfaction error
Adds a prescriptive position showing for a method that
didn't satisfy an interface.

With this change, we shall now see:

    *myS does not implement S (wrong type for DoSomething method)
        have DoSomething() (string, error) at ./main.go:9:14
	want DoSomething() (int, error)

instead of previously:

    *myS does not implement S (wrong type for DoSomething method)
        have DoSomething() (string, error)
	want DoSomething() (int, error)

Fixes #42841

Change-Id: I66990929e39b0d36f2e91da0d92f60586a9b84e5