Update patch set 27
Patch Set 27:

This is the final stretch :D :D :D

So I think I can just modify the test them self right to pass? And are all expected behaviors with the new error interface right? So only the tests need to be adapted not the code?

--- FAIL: TestStringer (0.00s)
    content_test.go:438: expected "error=7" got "{7}"
FAIL
FAIL    html/template   0.053s

--- FAIL: TestExecute (0.01s)
    exec_test.go:792: W{888}.Error(): expected
                "-[888]-"
        got
                "-{888}-"
    exec_test.go:792: &W{999}.Error(): expected
                "-[999]-"
        got
                "-{999}-"
    exec_test.go:792: (*W)(nil).Error(): expected
                "-nilW-"
        got
                "-<nil>-"
FAIL
FAIL    text/template   0.044s

--- FAIL: TestPanicDeadlockGosched (0.01s)
    crash_test.go:95: testprog GoschedInPanic exit status: exit status 2
    crash_test.go:437: output does not start with "panic: errorThatGosched\n\n":
        panic: (main.errorThatGosched) (0x10e6ee0,0x11f3060)
        
        goroutine 1 [running]:
        main.GoschedInPanic()
                /usr/local/go/src/runtime/testdata/testprog/deadlock.go:170 +0x39
        main.main()
                /usr/local/go/src/runtime/testdata/testprog/main.go:34 +0x1cc
--- FAIL: TestPanicDeadlockSyscall (0.01s)
    crash_test.go:95: testprog SyscallInPanic exit status: exit status 2
    crash_test.go:437: output does not start with "1\n2\npanic: 3\n\n":
        panic: (main.errorThatPrint) (0x10e6f60,0x11f3060)
        
        goroutine 1 [running]:
        main.SyscallInPanic()
                /usr/local/go/src/runtime/testdata/testprog/deadlock.go:182 +0x39
        main.main()
                /usr/local/go/src/runtime/testdata/testprog/main.go:34 +0x1cc
--- FAIL: TestPanicLoop (0.01s)
    crash_test.go:95: testprog PanicLoop exit status: exit status 2
    crash_test.go:452: output does not contain "panic while printing panic value":
        panic: (*main.panicError) (0x10e40c0,0x11f3060)
        
        goroutine 1 [running]:
        main.PanicLoop()
                /usr/local/go/src/runtime/testdata/testprog/deadlock.go:230 +0x39
        main.main()
                /usr/local/go/src/runtime/testdata/testprog/main.go:34 +0x1cc
--- FAIL: TestCgoPanicDeadlock (0.07s)
    crash_test.go:95: testprogcgo CgoPanicDeadlock exit status: exit status 2
    crash_cgo_test.go:227: output does not start with "panic: cgo error\n\n":
        panic: (main.cgoError) (0x40f0c80,0x4205010)
        
        goroutine 1 [running]:
        main.CgoPanicDeadlock()
                /usr/local/go/src/runtime/testdata/testprogcgo/deadlock.go:29 +0x39
        main.main()
                /usr/local/go/src/runtime/testdata/testprogcgo/main.go:34 +0x1cc
FAIL
FAIL    runtime 25.510s

Patch-set: 27
Reviewer: Gerrit User 15355 <15355@62eb7196-b449-3ce5-99f1-c037f21e1705>