Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> > Do you have runnable example on Linux? Maybe we could run its equivalent on Windows.
> 
> This program completes because on Unix systems syscall.Errno.Temporary returns true for EMFILE.  If it did not, this program would fail with an error "open /tmp/enfileNNN: too many open files".
> 

Windows obviously does not have unix.Setrlimit. So I just upped the limit to 2000 to make program crash, otherwise it succeeds. This is my program

```
package main

import (
	"errors"
	"fmt"
	//"golang.org/x/sys/unix"
	"io/ioutil"
	"log"
	"os"
	"sync"
	"syscall"
	"time"
)

func main() {
	const limit = 2000
	//if err := unix.Setrlimit(unix.RLIMIT_NOFILE, &unix.Rlimit{limit, limit}); err != nil {
	//	log.Fatal(err)
	//}
	var wg sync.WaitGroup
	for i := 0; i < 2*limit; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			for {
				f, err := ioutil.TempFile("", "enfile")
				if err != nil {
					var errno syscall.Errno
					if errors.As(err, &errno) && errno.Temporary() {
						fmt.Printf("failed: %v\n", err)
						time.Sleep(time.Millisecond)
					} else {
						log.Fatal(err)
					}
					continue
				}
				fmt.Printf("opened %d file\n", i)
				defer os.Remove(f.Name())
				time.Sleep(time.Second)
				f.Close()
				return
			}
		}(i)
	}
	wg.Wait()
}

```

This is beginning of the crash message

```
opened 3869 file
opened 3870 file
opened 3871 file
opened 3872 file
opened 3873 file
opened 3874 file
opened 3875 file
opened 3876 file
opened 3877 file
opened 3878 file
opened 3879 file
opened 3880 file
opened 3881 file
opened 3882 file
opened 3883 file
opened 3884 file
opened 3885 file
opened 3887 file
opened 3889 file
opened 3891 file
opened 3897 file
runtime: failed to create new OS thread (have 1231 already; errno=8)
fatal error: runtime.newosproc

runtime stack:
runtime.throw(0x4c3f5a, 0x11)
	/home/a/go/src/runtime/panic.go:1112 +0x64
runtime.newosproc(0x12ea8960)
	/home/a/go/src/runtime/os_windows.go:787 +0x142
runtime.newm1(0x12ea8960)
	/home/a/go/src/runtime/proc.go:1789 +0xbd
runtime.newm(0x0, 0x11816000)
	/home/a/go/src/runtime/proc.go:1768 +0x71
runtime.startm(0x11816000, 0x1181a200)
	/home/a/go/src/runtime/proc.go:1905 +0xf7
runtime.handoffp(0x11816000)
	/home/a/go/src/runtime/proc.go:1932 +0x49
runtime.retake(0xb0b6e2b8, 0x98, 0x98)
	/home/a/go/src/runtime/proc.go:4630 +0x170
runtime.sysmon()
	/home/a/go/src/runtime/proc.go:4539 +0x1d6
runtime.mstart1()
	/home/a/go/src/runtime/proc.go:1133 +0x9b
runtime.mstart()
	/home/a/go/src/runtime/proc.go:1098 +0x51

```

So my program run out of threads. There is no EMFILE error here.

Patch-set: 5
Reviewer: Gerrit User 5070 <5070@62eb7196-b449-3ce5-99f1-c037f21e1705>