Update patch set 3
Patch Set 3:

> I don't think an explicit test is needed, because TestTransportEventTrace_h2 already fails if the other w.pc.alt == nil check is missing.
> 
> --- FAIL: TestTransportEventTrace_h2 (0.00s)

When I run it with or without your change I don't see a failure.
Is there some other tweak you had to do to cause the failure?
It should be fine to modify this test in the h2 case as your test case but right now it doesn't fail for me.

Patch-set: 3
Reviewer: Gerrit User 5889 <5889@62eb7196-b449-3ce5-99f1-c037f21e1705>