Update patch set 1
Patch Set 1:

Thank you for working on this Han, and thank you Ian for the review!

Han, we are close to rolling out Go1.12 but since this CL was made ~6months ago and is not invasive I'll make a plea on your behalf that we let it in as it will help a lot with developer productivity too.
IN regards to a test, here is something that can lock this behavior in an prevent future regressions:


// Ensure that panics in sub tests will still allow previous
// output to be printed before exiting. See Issue #25021.
func TestSubTestPanicPrintsOutput(t *testing.T) {
        testenv.MustHaveGoBuild(t)
        tempDir, err := ioutil.TempDir("", "issue-25021")
        if err != nil {
                t.Fatalf("Failed to create temp directory: %v", err)
        }
        defer os.RemoveAll(tempDir)

        code := `
package main

import "testing"

func TestX(t *testing.T) {
        t.Run("A", func(t *testing.T) {
                t.Log("hi!")
                t.Fatal("hello!")
        })

        t.Run("B", func(t *testing.T) {
                panic("goodbye!")
        })
}`
        destFile := filepath.Join(tempDir, "issue25021_test.go")
        if err := ioutil.WriteFile(destFile, []byte(code), 0644); err != nil {
                t.Fatalf("Failed to save test code: %v", err)
        }

        got, err := exec.Command(testenv.GoToolPath(t), "test", destFile).CombinedOutput()
        if err == nil {
                t.Fatal("The command unexpectedly passed")
        }

        want := []byte(
                `    --- FAIL: TestX/A (0.00s)
        issue25021_test.go:8: hi!
        issue25021_test.go:9: hello!
    --- FAIL: TestX/B (0.00s)
        panic: goodbye!
panic: goodbye! [recovered]
        panic: goodbye!
`)

        if !bytes.HasPrefix(got, want) {
                t.Errorf("Did not print previous output\nGot:\n%s\n\nWant prefix:\n%s", got, want)
        }
}

Patch-set: 1
CC: Gerrit User 5137 <5137@62eb7196-b449-3ce5-99f1-c037f21e1705>