Update patch set 3
Patch Set 3:

This CL has failed the run. Reason:

Tryjob [golang/try/x_tools-gotip-linux-amd64](https://cr-buildbucket.appspot.com/build/8747246410331548289) has failed with summary ([view all results](https://go-review.googlesource.com/c/587220?checksPatchset=3&tab=checks)):

---
**FAILURE**

* go on master ([change 587220](https://go-review.googlesource.com/c/go/+/587220/3))
* tools on master ([commit 32cec11](https://go.googlesource.com/tools/+/32cec1159814d8eea14ddf0687b4e5767b83c53c))

Error: `failed to run "make.bash": exit status 2`

Links:
* ["make.bash" (combined output)](https://logs.chromium.org/logs/golang/buildbucket/cr-buildbucket/8747246410331548289/+/u/step/13/log/2)

Patch-set: 3
Tag: autogenerated:cq:dry-run:1716372776
Attention: {"person_ident":"Gerrit User 5056 \u003c5056@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"ADD","reason":"ps#3: Tryjobs failed"}