net: adding IsNotFound to DNSError returned from cgo reverse resolution
The UNIX cgo resolver code didn't set `IsNotFound` on the DNSError returned when the `getnameinfo` call used for reverse resolution in `cgoNameinfoPTR` returns `EAI_NONAME`. This diff sets `IsNotFound` to true in that case.

`EAI_NONAME` is set by `getnameinfo` when the address resolution fails, and is defined in Solaris, OpenBSD, AIX, Darwin, Linux, NetBSD and DragonflyBSD according to online manpages I've checked. I have only tested on Darwin though.

```
$ ./all.bash
[...]
ALL TESTS PASSED
```

Then, I made a small go program to verify the behaviour:
```
package main

import (
  "fmt"
  "net"
)

func main() {
  names, err := net.LookupAddr("::2")
  fmt.Printf("names: %+v\n", names)

  if dnsErr, ok := err.(*net.DNSError); ok {
    fmt.Printf("error: %+v\n", *dnsErr)
  }
}
```

Before changes:
```
./dnstest
names: []
error: {Err:nodename nor servname provided, or not known Name:::2 Server: IsTimeout:false IsTemporary:false IsNotFound:false}
```

After changes:
```
$ ./dnstest
names: []
error: {Err:no such host Name:::2 Server: IsTimeout:false IsTemporary:false IsNotFound:true}
```

Change-Id: I95215b5b1a880ee3d616cbca5c6800af53106092
GitHub-Last-Rev: f2de83684feee03e7e697c5860626e2251f8f7a2
GitHub-Pull-Request: golang/go#45959