Update patch set 3
Patch Set 3:

This CL has failed the run. Reason:

Tryjob [golang/try/x_tools-gotip-linux-amd64](https://cr-buildbucket.appspot.com/build/8750147100770372833) has failed with summary ([view all results](https://go-review.googlesource.com/c/580536?checksPatchset=3&tab=checks)):

---
**FAILURE**

* go on master ([change 580536](https://go-review.googlesource.com/c/go/+/580536/3))
* tools on master ([commit daf9460](https://go.googlesource.com/tools/+/daf94608b5e2caf763ba634b84e7a5ba7970e155))

Error: `failed to run "make.bash": exit status 2`

Links:
* ["make.bash" (combined output)](https://logs.chromium.org/logs/golang/buildbucket/cr-buildbucket/8750147100770372833/+/u/step/11/log/2)

Patch-set: 3
Tag: autogenerated:cq:dry-run:1713606461
Attention: {"person_ident":"Gerrit User 64033 \u003c64033@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"ADD","reason":"ps#3: Tryjobs failed"}