Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 2: TryBot-Result-1
> > 
> > 2 of 21 TryBots failed:
> > Failed on linux-amd64: https://storage.googleapis.com/go-build-log/f60060c0/linux-amd64_55934609.log
> > Failed on windows-amd64-2016: https://storage.googleapis.com/go-build-log/f60060c0/windows-amd64-2016_86741e53.log
> > 
> > Consult https://build.golang.org/ to see whether they are new failures. Keep in mind that TryBots currently test *exactly* your git commit, without rebasing. If your commit's git parent is old, the failure might've already been fixed.
> 
> I'm not sure how to fix this test failure. I've run all.bash a bunch of times on two different machines and I can't reproduce it locally.
> 
> Unfortunately, while doing that, I found that the test for this actual feature flakes too:
> 
>   --- FAIL: TestScript (0.00s)
>       --- FAIL: TestScript/test_init (0.46s)
>           script_test.go:191:
>               # Tests for automatic testing.Init calls when using 'go test'. (0.000s)
>               # Tests running under 'go test' should observe that testing.Init is called
>               # before any user package initialization code runs.
>               # A TestMain should be able to access testing flags if it calls flag.Parse
>               # without needing to use testing.Init.
>               # Though it is ill-advised, a dependency of a test should be able to call
>               # flag.Parse during initialization without breaking 'go test' as long as it
>               # imports "testing". See golang.org/issue/31859. (0.462s)
>               > go test
>               [stdout]
>               flag provided but not defined: -test.timeout
>               Usage of $WORK/tmp/go-build105843022/b001/m.test:
>               exit status 2
>               FAIL        m       0.005s
>               [exit status 1]
>               FAIL: testdata/script/test_init.txt:12: unexpected command failure
> 
> So I guess I'm misunderstanding some aspect of the build caching here. I thought that things would work out because the cache key includes a list of the files that went into the build, so there should be two separate artifacts for the test and non-test versions of the testing package.
> 
> Bryan, any pointers?

I looked into this but I still can't explain the behavior you observed.
The list of inputs to the cache key¹ does not include IgnoredGoFiles, but does include GoFiles.

¹https://github.com/golang/go/blob/80cca23b59fe75ba588f7ddee7adb48a6afe2eb7/src/cmd/go/internal/work/exec.go#L301-L314

Patch-set: 2
Reviewer: Gerrit User 6365 <6365@62eb7196-b449-3ce5-99f1-c037f21e1705>