Update patch set 4
Change has been successfully cherry-picked as ada95e2807abbbab990c5c13a271e823e4e0a5cc

2 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: src/net/net_test.go
Insertions: 1, Deletions: 0.

@@ -551,6 +551,7 @@
 		}
 		// TODO: during an open development cycle, try making this a failure
 		// and see whether it causes the test to become flaky anywhere else.
+		return
 	}
 	if ne, ok := err.(Error); !ok {
 		t.Errorf("Read error does not implement net.Error: %v", err)
```


Patch-set: 4
Subject: net: in TestNotTemporaryRead, do not assume that a dialed connection has been accepted
Status: merged
Commit: ada95e2807abbbab990c5c13a271e823e4e0a5cc
Tag: autogenerated:gerrit:merged
Groups: f57fbb27036e5bdfa3b508bcd14294b884769bcc
Label: Code-Review=+2, 57f7523222b03940ce3e4361833567212c9bcfcf Gerrit User 5137 <5137@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: Code-Review=+2, 69bbe9cc5f3dcb1ee54f222f63c354c5480f9ed3 Gerrit User 5206 <5206@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: Trust=+1, 3d3dd3b3dce48359cacb8d78fba94b17891f3503
Label: Run-TryBot=+1, 381e211053691d39fa9435e3be93c5f748cc7c6f
Label: TryBot-Result=+1, bdddc051f173d10439335c27a75c1717528a996b Gerrit User 5976 <5976@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: SUBM=+1, 13a5ec8a08057d5355c52f422e8c643863879084
Submission-id: 385314
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~PrologRule
Submitted-with: MAY: Auto-Submit
Submitted-with: MAY: TryBot-Result
Submitted-with: MAY: Run-TryBot
Submitted-with: MAY: Trust
Submitted-with: OK: Code-Review: Gerrit User 5206 <5206@62eb7196-b449-3ce5-99f1-c037f21e1705>
Submitted-with: OK: Trusted: Gerrit User 5976 <5976@62eb7196-b449-3ce5-99f1-c037f21e1705>
Attention: {"person_ident":"Gerrit User 5206 \u003c5206@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"REMOVE","reason":"Change was submitted"}