Update patch set 4
Patch Set 4:

I added a test to `runtime/race/output_test.go` called `mutex` that checks for the inverted semaphore case.  Unsurprisingly, the test passes on Go and fails on my first attempt to address [issue 37355](https://github.com/golang/go/issues/37355).  As Dmitry pointed out, my original patch breaks the inverted semaphore case.

I have now updated the original patch to properly address the GitHub issue without breaking inverted semaphores.  In other words, we pass `chanmm` in `output_test.go` (by flagging the race described in issue 37355) and we pass `mutex` (by properly respecting the "backward" happens-before rule required by inverted semaphores).

The patch does cause lots of errors when running `all.bash`.  I suspect that the culprits might be:

- The patch involves an additional field in the `hchan` struct and a bit more memory allocation per channel.  It looks to me like there are memory consumption checks and safeguards built into some of the tests.  If that's the case, the patch is likely breaking those checks:

```
--- FAIL: TestHello (0.17s)
    pack_test.go:338: [/Users/danielsf/go/bin/go build cmd/pack]: exit status 2
        runtime: nelems=56 nalloc=2 previous allocCount=1 nfreed=65535
        fatal error: sweep increased allocation count
```

- Another possible explanation for the errors in `all.bash` may be that the patch is uncovering latent synchronization issues.  That would be super.
- Another possibility is that I made a mistake in the patch :)
- Perhaps something else?

I'll write down and send a note describing the patch, and why I believe it fixes the issue it is supposed to address without breaking inverted semaphores.

Also, I'll be happy to look at the errors in `all.bash`.

Patch-set: 4