Update patch set 4
Patch Set 4:

Matthew, can you give me a hand on this? I cannot see how to fix this test:

go test go/internal/gcimporter
--- FAIL: TestVersionHandling (0.00s)
    gcimporter_test.go:159: import "./test_go1.11_0i" failed: cannot import "testdata/versions/test_go1.11_0i" (unknown iexport format version 0), possibly version skew - reinstall package
FAIL
FAIL	go/internal/gcimporter	0.863s

I thought I have done everything required to increment the export version.

Thank you!

Patch-set: 4
Reviewer: Gerrit User 5440 <5440@62eb7196-b449-3ce5-99f1-c037f21e1705>
Reviewer: Gerrit User 26536 <26536@62eb7196-b449-3ce5-99f1-c037f21e1705>