Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> Richard, I think there are still errors in this change. When I ran Elias' wasm benchmark with this new change, I am getting the same compilation error which I got when I was trying to add this myself.
> 
> You can just clone this repo - https://git.sr.ht/~eliasnaur/gio. Follow the platform specific installation instructions. And then from the apps directory, run the benchmark. You will see:
> 
> 12:12:55-agniva-~/play/gio/apps$GOOS=js GOARCH=wasm gotip test -exec=$HOME/play/gosource/go/misc/wasm/go_js_wasm_exec -bench=. ./gophers/ 
> [CompileError: AsyncCompile: Compiling wasm function #7657:<?> failed: set_local[0] expected type f64, found get_local of type f32 @+7276096]
> exit status 1
> FAIL	gioui.org/apps/gophers	4.634s
> FAIL

Actually, no need to go that far. cmd/compile/internal/gc also fails.

12:31:32-agniva-~/play/gosource/go/src$GOOS=js GOARCH=wasm gotip test -exec=$HOME/play/gosource/go/misc/wasm/go_js_wasm_exec -v ./cmd/compile/internal/gc
[CompileError: AsyncCompile: Compiling wasm function #6675:<?> failed: call[0] expected type f64, found f32.load of type f32 @+9187579]
FAIL	cmd/compile/internal/gc	2.257s
FAIL

Patch-set: 1
Reviewer: Gerrit User 24096 <24096@62eb7196-b449-3ce5-99f1-c037f21e1705>