Update patch set 7
Patch Set 7:

This CL has failed the run. Reason:

Tryjob [golang/try/x_tools-gotip-linux-amd64](https://cr-buildbucket.appspot.com/build/8763795564851343505) has failed with summary [(view all results)](https://go-review.googlesource.com/c/511516?checksPatchset=7&tab=checks):

---
**FAILURE**

* go on master ([change 511516](https://go-review.googlesource.com/c/go/+/511516/7))
* tools on master ([commit 53ad329](https://go.googlesource.com/tools/+/53ad329bd98f6eea2106d46f2c1655cbbdd28242))

error: failed to run "test golang.org/x/tools module": exit status 1
failed to run "test golang.org/x/tools/gopls module": exit status 1
* ["test golang.org/x/tools module" (combined output)](https://logs.chromium.org/logs/golang/buildbucket/cr-buildbucket/8763795564851343505/+/u/step/25/log/2)
* ["test golang.org/x/tools/gopls module" (combined output)](https://logs.chromium.org/logs/golang/buildbucket/cr-buildbucket/8763795564851343505/+/u/step/26/log/2)

Patch-set: 7
Tag: autogenerated:cq:dry-run:1700590267
Attention: {"person_ident":"Gerrit User 5305 \u003c5305@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"ADD","reason":"ps#7: Tryjobs failed"}