net/http: convert URL credentials to Authorization header for js fetch
The fetch JS API will refuse to accept URLs that contain credentials:

    > fetch("https://user:pass@example.com")
    TypeError: Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials

However the non-JS http.RoundTripper does accept URLs with credentials.
By converting the credentials to an Authorization header, we can have parity.
This header is added only if Authorization header is not already set.

Change-Id: Iaeb95945f894b02640b37a2e572c4aec6811af8b
GitHub-Last-Rev: af7b54ceae1be80a9cb14a2b668f9eeb60b28ffa
GitHub-Pull-Request: golang/go#56564