Update patch set 4
Patch Set 4:

FYI, since this CL, dragonfly-amd64 is consistently failing with:

    --- FAIL: TestCgoExternalThreadSignal (7.02s)
    	crash_cgo_test.go:94: expected "OK\n", but got "C signal did not crash as expected\n\n\n"

Patch-set: 4
Reviewer: Gerrit User 5440 <5440@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: Code-Review=0