Update patch set 6
Patch Set 6:

This CL introduced a new test failure for android-arm builder.
It's concerning to see syscall.Setenv overwrites 'want' as shown in the failure log.

--- FAIL: TestFixedGOROOT (0.00s)
	env_test.go:33: after setenv runtime.GOROOT()="/data/local/tmp/goroot", want "/os\x00a/local/tmp/goroot"
	env_test.go:39: after unsetenv runtime.GOROOT()="/data/local/tmp/goroot", want "/os\x00a/local/tmp/goroot"
FAIL
exitcode=1go_android_exec: adb shell rm -rf /data/local/tmp/runtime.test-34925
FAIL	runtime	33.962s

Patch-set: 6
Reviewer: Gerrit User 5190 <5190@62eb7196-b449-3ce5-99f1-c037f21e1705>
Label: Code-Review=0