Update patch set 16
Patch Set 16:

(1 comment)

Thank you very much I think you made it :D The only thing left is for me to go through the std lib cleaning up, but the hard part is over now I think :D

gert@gert /usr/local/go/src:#32913> ./all.bash 
Building Go cmd/dist using /usr/local/go1.
Building Go toolchain1 using /usr/local/go1.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for darwin/amd64.
# compress/bzip2
src/compress/bzip2/bzip2.go:63:26: cannot use StructuralError("bad magic value") (type StructuralError) as type error in return argument:
        StructuralError does not implement error (missing Unwrap method)

Patch-set: 16
Reviewer: Gerrit User 15355 <15355@62eb7196-b449-3ce5-99f1-c037f21e1705>