crypto/elliptic: use generics for nistec-based curves
There was no way to use an interface because the methods on the Point
types return concrete Point values.

Mostly an experiment to see if generics would help. I'd say they do!

This crypto/ecdsa failure looks like a bug. I would expect a pointer to
a generic value to be comparable like any other pointer.

    --- FAIL: TestEqual (0.00s)
        --- FAIL: TestEqual/P224 (0.00s)
            equal_test.go:32: x509: unknown curve while marshaling to PKCS#8
        --- FAIL: TestEqual/P384 (0.00s)
            equal_test.go:32: x509: unknown curve while marshaling to PKCS#8
        --- FAIL: TestEqual/P521 (0.00s)
            equal_test.go:32: x509: unknown curve while marshaling to PKCS#8
    FAIL
    FAIL	crypto/ecdsa	0.367s

Three somewhat minor annoyances:

    - Allocations went up due to #48849. This is fine here, where
      math/big causes allocations anyway, but would probably not be fine
      in nistec itself.

    - Carrying the newPoint/newGenerator functions around as a field is
      a little weird, even if safe.

    - What were top level functions became methods because they need
      access to the type parameter, even if they don't need access to
      the receiver.

Change-Id: I050f3a27f15d3f189818da80da9de0cba0548931