Update patch set 11
Patch Set 11:

(3 comments)

I changed your CL so your new code runs on Windows, like
```
diff --git a/src/runtime/os_windows.go b/src/runtime/os_windows.go
index aef18dd..7bc037e 100644
--- a/src/runtime/os_windows.go
+++ b/src/runtime/os_windows.go
@@ -192,7 +192,8 @@ func loadOptionalSyscalls() {
 	}
 	_NtWaitForSingleObject = windowsFindfunc(n32, []byte("NtWaitForSingleObject\000"))
 
-	if windowsFindfunc(n32, []byte("wine_get_version\000")) != nil {
+	//if windowsFindfunc(n32, []byte("wine_get_version\000")) != nil {
+	if true {
 		// running on Wine
 		initWine(k32)
 	}
```
and run all.bat. A lot of tests failed:
```
ok      math/bits       -0.000s
ok      math/cmplx      -0.001s
ok      math/rand       0.001s
ok      mime    -0.000s
ok      mime/multipart  -0.001s
ok      mime/quotedprintable    -0.000s
--- FAIL: TestWriteTimeoutFluctuation (-0.00s)
        timeout_test.go:772: unexpected type on 1st nested level: *errors.errorString
        timeout_test.go:775: Write took -571.344µs; expected 100ms
--- FAIL: TestReadFromTimeoutFluctuation (-0.00s)
        timeout_test.go:730: unexpected type on 1st nested level: *errors.errorString
        timeout_test.go:733: ReadFrom took -317.656µs; expected 100ms
--- FAIL: TestReadTimeoutFluctuation (0.00s)
        timeout_test.go:697: unexpected type on 1st nested level: *errors.errorString
        timeout_test.go:700: Read took 103.588µs; expected 100ms
FAIL
FAIL    net     -0.006s
--- FAIL: TestServerTimeouts (-0.00s)
        serve_test.go:505: got EOF after 60.628µs, want >= 200ms
FAIL
FAIL    net/http        -0.005s
ok      net/http/cgi    -0.000s
ok      net/http/cookiejar      -0.001s
ok      net/http/fcgi   -0.001s
ok      net/http/httptest       -0.001s
ok      net/http/httptrace      -0.001s
ok      net/http/httputil       -0.000s
ok      net/http/internal       -0.000s
ok      net/internal/socktest   -0.000s
ok      net/mail        -0.000s
ok      net/rpc -0.001s
ok      net/rpc/jsonrpc -0.000s
ok      net/smtp        -0.001s
ok      net/textproto   -0.000s
ok      net/url 0.000s
ok      os      -0.001s
ok      os/exec -0.003s
ok      os/signal       -0.001s
ok      os/user -0.000s
ok      path    -0.001s
ok      path/filepath   -0.001s
ok      reflect -0.000s
ok      regexp  -0.000s
ok      regexp/syntax   -0.001s
--- FAIL: TestCgoCheckBytes (-0.00s)
        crash_cgo_test.go:227: cgo check too slow: got -121.999µs, expected at most -5.66904ms
FAIL
FAIL    runtime -0.025s
ok      runtime/debug   -0.000s
ok      runtime/internal/atomic -0.000s
ok      runtime/internal/sys    -0.000s
panic: test timed out after 3m0s

goroutine 35 [running]:
testing.startAlarm.func1()
        c:/Users/Alex/dev/go/src/testing/testing.go:1029 +0x100
created by time.goFunc
        c:/Users/Alex/dev/go/src/time/sleep.go:170 +0x4b

goroutine 1 [chan receive, 2 minutes]:
testing.(*T).Run(0xc042070270, 0x5f71d2, 0xe, 0x6033b8, 0x480401)
        c:/Users/Alex/dev/go/src/testing/testing.go:702 +0x30b
testing.runTests.func1(0xc042070270)
        c:/Users/Alex/dev/go/src/testing/testing.go:888 +0x6e
testing.tRunner(0xc042070270, 0xc042055e10)
        c:/Users/Alex/dev/go/src/testing/testing.go:659 +0x9f
testing.runTests(0xc04203ce00, 0x6e1a00, 0x10, 0x10, 0xc04203b128)
        c:/Users/Alex/dev/go/src/testing/testing.go:886 +0x2c8
testing.(*M).Run(0xc042055f20, 0xc042055f78)
        c:/Users/Alex/dev/go/src/testing/testing.go:828 +0x103
main.main()
        runtime/pprof/_test/_testmain.go:78 +0xe2

goroutine 33 [runnable]:
time.Since(0xbe3535faa7c80c04, 0xfffffffffffdb96e, 0x6e3c40, 0xfffffffffa0e76ae)
        c:/Users/Alex/dev/go/src/time/time.go:882 +0x81
runtime/pprof_test.cpuHogger(0x603470, 0xbebc200)
        c:/Users/Alex/dev/go/src/runtime/pprof/pprof_test.go:33 +0x94
runtime/pprof_test.TestCPUProfile.func1(0xbebc200)
        c:/Users/Alex/dev/go/src/runtime/pprof/pprof_test.go:72 +0x3e
runtime/pprof_test.testCPUProfile(0xc0420700d0, 0xc0420b1f88, 0x1, 0x1, 0x603388)
        c:/Users/Alex/dev/go/src/runtime/pprof/pprof_test.go:140 +0x124
runtime/pprof_test.TestCPUProfile(0xc0420700d0)
        c:/Users/Alex/dev/go/src/runtime/pprof/pprof_test.go:71 +0x72
testing.tRunner(0xc0420700d0, 0x6033b8)
        c:/Users/Alex/dev/go/src/testing/testing.go:659 +0x9f
created by testing.(*T).Run
        c:/Users/Alex/dev/go/src/testing/testing.go:701 +0x2e1

goroutine 34 [sleep]:
time.Sleep(0x5f5e100)
        c:/Users/Alex/dev/go/src/runtime/time.go:64 +0x142
runtime/pprof.profileWriter(0x6ca4c0, 0xc042096a10)
        c:/Users/Alex/dev/go/src/runtime/pprof/pprof.go:711 +0x55
created by runtime/pprof.StartCPUProfile
        c:/Users/Alex/dev/go/src/runtime/pprof/pprof.go:696 +0x129
FAIL    runtime/pprof   -0.101s
ok      runtime/trace   -0.001s
ok      sort    -0.000s
ok      strconv -0.001s
ok      strings -0.000s
ok      sync    -0.000s
ok      sync/atomic     -0.000s
ok      syscall -0.000s
panic: test timed out after 3m0s

goroutine 343 [running]:
testing.startAlarm.func1()
        c:/Users/Alex/dev/go/src/testing/testing.go:1029 +0x100
created by time.goFunc
        c:/Users/Alex/dev/go/src/time/sleep.go:170 +0x4b

goroutine 1 [chan receive, 2 minutes]:
testing.(*T).Run(0xc042070340, 0x5a71c9, 0xd, 0x5b1f30, 0x487801)
        c:/Users/Alex/dev/go/src/testing/testing.go:702 +0x30b
testing.runTests.func1(0xc042070340)
        c:/Users/Alex/dev/go/src/testing/testing.go:888 +0x6e
testing.tRunner(0xc042070340, 0xc042055df8)
        c:/Users/Alex/dev/go/src/testing/testing.go:659 +0x9f
testing.runTests(0xc04203cde0, 0x66fd40, 0x10, 0x10, 0xc042078c68)
        c:/Users/Alex/dev/go/src/testing/testing.go:886 +0x2c8
testing.(*M).Run(0xc0420b9f20, 0xc04206e780)
        c:/Users/Alex/dev/go/src/testing/testing.go:828 +0x103
testing_test.TestMain(0xc042055f20)
        c:/Users/Alex/dev/go/src/testing/testing_test.go:17 +0x32
main.main()
        testing/_test/_testmain.go:76 +0xe2

goroutine 340 [chan receive, 2 minutes]:
testing.(*B).doBench(0xc04205e420, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:267 +0xa1
testing.(*B).run(0xc04205e420, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:260 +0xf0
testing.Benchmark(0x5b1f10, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:660 +0x11f
testing.TestBenchmark(0xc0420d0750)
        c:/Users/Alex/dev/go/src/testing/sub_test.go:591 +0x46
testing.tRunner(0xc0420d0750, 0x5b1f30)
        c:/Users/Alex/dev/go/src/testing/testing.go:659 +0x9f
created by testing.(*T).Run
        c:/Users/Alex/dev/go/src/testing/testing.go:701 +0x2e1

goroutine 29 [chan receive (nil chan), 2 minutes]:
testing.(*T).Parallel(0xc0420a8680)
        c:/Users/Alex/dev/go/src/testing/testing.go:591 +0x14c
testing.TestTRun.func10(0xc0420a8680)
        c:/Users/Alex/dev/go/src/testing/sub_test.go:288 +0x32
testing.tRunner(0xc0420a8680, 0x5b1fc0)
        c:/Users/Alex/dev/go/src/testing/testing.go:659 +0x9f
created by testing.(*T).Run
        c:/Users/Alex/dev/go/src/testing/testing.go:701 +0x2e1

goroutine 93 [runnable]:
time.Sleep(0xf4240)
        c:/Users/Alex/dev/go/src/runtime/time.go:64 +0x142
testing.TestBenchmark.func1.1(0xc04205e000)
        c:/Users/Alex/dev/go/src/testing/sub_test.go:595 +0x49
testing.(*B).runN(0xc04205e000, 0xc350)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:147 +0xb9
testing.(*B).launch(0xc04205e000)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:297 +0x128
created by testing.(*B).doBench
        c:/Users/Alex/dev/go/src/testing/benchmark.go:266 +0x77

goroutine 341 [chan receive, 2 minutes]:
testing.(*B).doBench(0xc04205e000, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:267 +0xa1
testing.(*B).run(0xc04205e000, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:260 +0xf0
testing.(*B).Run(0xc04205e420, 0x0, 0x0, 0x5b1f08, 0x3f000)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:517 +0x273
testing.TestBenchmark.func1(0xc04205e420)
        c:/Users/Alex/dev/go/src/testing/sub_test.go:593 +0x5d
testing.(*B).runN(0xc04205e420, 0x64)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:147 +0xb9
testing.(*B).launch(0xc04205e420)
        c:/Users/Alex/dev/go/src/testing/benchmark.go:297 +0x128
created by testing.(*B).doBench
        c:/Users/Alex/dev/go/src/testing/benchmark.go:266 +0x77
FAIL    testing -0.101s
ok      testing/quick   -0.000s
ok      text/scanner    -0.000s
ok      text/tabwriter  -0.000s
ok      text/template   -0.000s
ok      text/template/parse     -0.000s
--- FAIL: TestSleep (-0.00s)
        sleep_test.go:40: Sleep(100ms) slept for only -209.85µs
--- FAIL: TestAfter (-0.00s)
        sleep_test.go:170: After(100ms) slept for only -321000 ns
--- FAIL: TestAfterTick (-0.00s)
        sleep_test.go:191: 10 ticks of 10ms too fast: took -142.462µs, expected 100ms
--- FAIL: TestAfterQueuing (-0.00s)
        sleep_test.go:231: attempt 0 failed: After(20ms) arrived at -83.454µs, expected [10ms,220ms]
        sleep_test.go:231: attempt 1 failed: After(70ms) arrived at -95.872µs, expected [35ms,770ms]
        sleep_test.go:231: attempt 2 failed: After(120ms) arrived at -125.974µs, expected [60ms,1.32s]
        sleep_test.go:231: attempt 3 failed: After(170ms) arrived at -153.44µs, expected [85ms,1.87s]
        sleep_test.go:231: attempt 4 failed: After(220ms) arrived at -178.754µs, expected [110ms,2.42s]
        sleep_test.go:235: After(220ms) arrived at -178.754µs, expected [110ms,2.42s]
--- FAIL: TestTicker (-0.00s)
        tick_test.go:26: 10 100ms ticks took -718.928µs, expected [800ms,1.2s]
FAIL
FAIL    time    -0.005s
ok      unicode -0.000s
ok      unicode/utf16   -0.000s
ok      unicode/utf8    -0.000s
ok      vendor/golang_org/x/crypto/chacha20poly1305     -0.000s
ok      vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20   -0.000s
ok      vendor/golang_org/x/crypto/curve25519   -0.000s
ok      vendor/golang_org/x/crypto/poly1305     -0.000s
ok      vendor/golang_org/x/net/http2/hpack     -0.000s
ok      vendor/golang_org/x/net/idna    -0.000s
ok      vendor/golang_org/x/net/lex/httplex     -0.000s
ok      cmd/addr2line   -0.001s
ok      cmd/api -0.000s
ok      cmd/asm/internal/asm    -0.000s
ok      cmd/asm/internal/lex    -0.001s
ok      cmd/compile     -0.003s
ok      cmd/compile/internal/gc -0.006s
ok      cmd/compile/internal/ssa        -0.000s
ok      cmd/compile/internal/syntax     -0.000s
ok      cmd/compile/internal/test       -0.000s [no tests to run]
ok      cmd/cover       -0.001s
ok      cmd/doc -0.001s
ok      cmd/fix -0.000s
ok      cmd/go  -0.070s
ok      cmd/go/internal/generate        -0.001s
ok      cmd/go/internal/get     -0.000s
ok      cmd/go/internal/load    -0.000s
ok      cmd/go/internal/work    -0.000s
ok      cmd/gofmt       -0.000s
ok      cmd/internal/goobj      -0.001s
ok      cmd/internal/obj        -0.000s
ok      cmd/internal/obj/arm64  0.000s
ok      cmd/internal/obj/x86    -0.001s
ok      cmd/internal/src        -0.000s
ok      cmd/link        -0.001s
ok      cmd/nm  -0.003s
ok      cmd/objdump     -0.001s
ok      cmd/pack        -0.001s
ok      cmd/trace       -0.001s
ok      cmd/vendor/golang.org/x/arch/arm/armasm -0.001s
ok      cmd/vendor/golang.org/x/arch/ppc64/ppc64asm     -0.001s
ok      cmd/vendor/golang.org/x/arch/x86/x86asm -0.000s
ok      cmd/vet -0.001s
ok      cmd/vet/internal/cfg    -0.000s
2017/04/17 16:34:00 Failed: exit status 1

c:\Users\Alex\dev\go\src>
```
Why? I would expect to see no failed tests?

Alex

Patch-set: 11
Reviewer: Gerrit User 5070 <5070@62eb7196-b449-3ce5-99f1-c037f21e1705>